package com.itcast.bulls.stock.dao.office;

import com.itcast.bulls.stock.entity.office.Tradestockquotelast;

public interface TradestockquotelastMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office.t_trade_stock_quote_last
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office.t_trade_stock_quote_last
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    int insert(Tradestockquotelast record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office.t_trade_stock_quote_last
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    int insertSelective(Tradestockquotelast record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office.t_trade_stock_quote_last
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    Tradestockquotelast selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office.t_trade_stock_quote_last
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    int updateByPrimaryKeySelective(Tradestockquotelast record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office.t_trade_stock_quote_last
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    int updateByPrimaryKey(Tradestockquotelast record);
}