// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/StockFinanceService.proto

package com.itcast.bulls.stock.struct.grpc.trade;

public interface GetAccountSettlementSingleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAccountSettlementSingle)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   **
   * 主键标识
   * </pre>
   *
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <pre>
   **
   * 用户ID
   * </pre>
   *
   * <code>int64 userId = 2;</code>
   */
  long getUserId();

  /**
   * <pre>
   **
   * 成交记录ID
   * </pre>
   *
   * <code>int64 dealId = 3;</code>
   */
  long getDealId();

  /**
   * <pre>
   **
   * 交易账号ID
   * </pre>
   *
   * <code>int64 accountId = 4;</code>
   */
  long getAccountId();

  /**
   * <pre>
   **
   * 交易时间
   * </pre>
   *
   * <code>int64 tradeTime = 5;</code>
   */
  long getTradeTime();

  /**
   * <pre>
   **
   * 股票ID
   * </pre>
   *
   * <code>int64 stockId = 6;</code>
   */
  long getStockId();

  /**
   * <pre>
   **
   * 股票代码
   * </pre>
   *
   * <code>string stockCode = 7;</code>
   */
  java.lang.String getStockCode();
  /**
   * <pre>
   **
   * 股票代码
   * </pre>
   *
   * <code>string stockCode = 7;</code>
   */
  com.google.protobuf.ByteString
      getStockCodeBytes();

  /**
   * <pre>
   **
   * 币种
   * </pre>
   *
   * <code>string currency = 8;</code>
   */
  java.lang.String getCurrency();
  /**
   * <pre>
   **
   * 币种
   * </pre>
   *
   * <code>string currency = 8;</code>
   */
  com.google.protobuf.ByteString
      getCurrencyBytes();

  /**
   * <pre>
   **
   * 买卖方向
   * </pre>
   *
   * <code>int32 direction = 9;</code>
   */
  int getDirection();

  /**
   * <pre>
   **
   * 交易金额
   * </pre>
   *
   * <code>int64 tradeAmount = 10;</code>
   */
  long getTradeAmount();

  /**
   * <pre>
   **
   * 交易数量
   * </pre>
   *
   * <code>int64 tradeVolume = 11;</code>
   */
  long getTradeVolume();

  /**
   * <pre>
   **
   * 交易价格
   * </pre>
   *
   * <code>int64 tradePrice = 12;</code>
   */
  long getTradePrice();

  /**
   * <pre>
   **
   * 税费（印花税+过户费+交易规费）
   * </pre>
   *
   * <code>int64 taxes = 13;</code>
   */
  long getTaxes();

  /**
   * <pre>
   **
   * 佣金
   * </pre>
   *
   * <code>int64 commission = 14;</code>
   */
  long getCommission();

  /**
   * <pre>
   **
   * 状态(0:有效， 1：锁定， 2：禁用）
   * </pre>
   *
   * <code>int32 status = 15;</code>
   */
  int getStatus();

  /**
   * <pre>
   **
   * 创建时间
   * </pre>
   *
   * <code>int64 createTime = 16;</code>
   */
  long getCreateTime();
}
