// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/StockFinanceService.proto

package com.itcast.bulls.stock.struct.grpc.trade;

/**
 * <pre>
 * 获取账户交易单返回数据结构
 * </pre>
 *
 * Protobuf type {@code GetAccountSettlementSingle}
 */
public  final class GetAccountSettlementSingle extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetAccountSettlementSingle)
    GetAccountSettlementSingleOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetAccountSettlementSingle.newBuilder() to construct.
  private GetAccountSettlementSingle(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetAccountSettlementSingle() {
    stockCode_ = "";
    currency_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetAccountSettlementSingle();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetAccountSettlementSingle(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 16: {

            userId_ = input.readInt64();
            break;
          }
          case 24: {

            dealId_ = input.readInt64();
            break;
          }
          case 32: {

            accountId_ = input.readInt64();
            break;
          }
          case 40: {

            tradeTime_ = input.readInt64();
            break;
          }
          case 48: {

            stockId_ = input.readInt64();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            stockCode_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            currency_ = s;
            break;
          }
          case 72: {

            direction_ = input.readInt32();
            break;
          }
          case 80: {

            tradeAmount_ = input.readInt64();
            break;
          }
          case 88: {

            tradeVolume_ = input.readInt64();
            break;
          }
          case 96: {

            tradePrice_ = input.readInt64();
            break;
          }
          case 104: {

            taxes_ = input.readInt64();
            break;
          }
          case 112: {

            commission_ = input.readInt64();
            break;
          }
          case 120: {

            status_ = input.readInt32();
            break;
          }
          case 128: {

            createTime_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.itcast.bulls.stock.struct.grpc.trade.StockFinanceServiceProto.internal_static_GetAccountSettlementSingle_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.itcast.bulls.stock.struct.grpc.trade.StockFinanceServiceProto.internal_static_GetAccountSettlementSingle_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle.class, com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <pre>
   **
   * 主键标识
   * </pre>
   *
   * <code>int64 id = 1;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int USERID_FIELD_NUMBER = 2;
  private long userId_;
  /**
   * <pre>
   **
   * 用户ID
   * </pre>
   *
   * <code>int64 userId = 2;</code>
   */
  public long getUserId() {
    return userId_;
  }

  public static final int DEALID_FIELD_NUMBER = 3;
  private long dealId_;
  /**
   * <pre>
   **
   * 成交记录ID
   * </pre>
   *
   * <code>int64 dealId = 3;</code>
   */
  public long getDealId() {
    return dealId_;
  }

  public static final int ACCOUNTID_FIELD_NUMBER = 4;
  private long accountId_;
  /**
   * <pre>
   **
   * 交易账号ID
   * </pre>
   *
   * <code>int64 accountId = 4;</code>
   */
  public long getAccountId() {
    return accountId_;
  }

  public static final int TRADETIME_FIELD_NUMBER = 5;
  private long tradeTime_;
  /**
   * <pre>
   **
   * 交易时间
   * </pre>
   *
   * <code>int64 tradeTime = 5;</code>
   */
  public long getTradeTime() {
    return tradeTime_;
  }

  public static final int STOCKID_FIELD_NUMBER = 6;
  private long stockId_;
  /**
   * <pre>
   **
   * 股票ID
   * </pre>
   *
   * <code>int64 stockId = 6;</code>
   */
  public long getStockId() {
    return stockId_;
  }

  public static final int STOCKCODE_FIELD_NUMBER = 7;
  private volatile java.lang.Object stockCode_;
  /**
   * <pre>
   **
   * 股票代码
   * </pre>
   *
   * <code>string stockCode = 7;</code>
   */
  public java.lang.String getStockCode() {
    java.lang.Object ref = stockCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stockCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **
   * 股票代码
   * </pre>
   *
   * <code>string stockCode = 7;</code>
   */
  public com.google.protobuf.ByteString
      getStockCodeBytes() {
    java.lang.Object ref = stockCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stockCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CURRENCY_FIELD_NUMBER = 8;
  private volatile java.lang.Object currency_;
  /**
   * <pre>
   **
   * 币种
   * </pre>
   *
   * <code>string currency = 8;</code>
   */
  public java.lang.String getCurrency() {
    java.lang.Object ref = currency_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      currency_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **
   * 币种
   * </pre>
   *
   * <code>string currency = 8;</code>
   */
  public com.google.protobuf.ByteString
      getCurrencyBytes() {
    java.lang.Object ref = currency_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      currency_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DIRECTION_FIELD_NUMBER = 9;
  private int direction_;
  /**
   * <pre>
   **
   * 买卖方向
   * </pre>
   *
   * <code>int32 direction = 9;</code>
   */
  public int getDirection() {
    return direction_;
  }

  public static final int TRADEAMOUNT_FIELD_NUMBER = 10;
  private long tradeAmount_;
  /**
   * <pre>
   **
   * 交易金额
   * </pre>
   *
   * <code>int64 tradeAmount = 10;</code>
   */
  public long getTradeAmount() {
    return tradeAmount_;
  }

  public static final int TRADEVOLUME_FIELD_NUMBER = 11;
  private long tradeVolume_;
  /**
   * <pre>
   **
   * 交易数量
   * </pre>
   *
   * <code>int64 tradeVolume = 11;</code>
   */
  public long getTradeVolume() {
    return tradeVolume_;
  }

  public static final int TRADEPRICE_FIELD_NUMBER = 12;
  private long tradePrice_;
  /**
   * <pre>
   **
   * 交易价格
   * </pre>
   *
   * <code>int64 tradePrice = 12;</code>
   */
  public long getTradePrice() {
    return tradePrice_;
  }

  public static final int TAXES_FIELD_NUMBER = 13;
  private long taxes_;
  /**
   * <pre>
   **
   * 税费（印花税+过户费+交易规费）
   * </pre>
   *
   * <code>int64 taxes = 13;</code>
   */
  public long getTaxes() {
    return taxes_;
  }

  public static final int COMMISSION_FIELD_NUMBER = 14;
  private long commission_;
  /**
   * <pre>
   **
   * 佣金
   * </pre>
   *
   * <code>int64 commission = 14;</code>
   */
  public long getCommission() {
    return commission_;
  }

  public static final int STATUS_FIELD_NUMBER = 15;
  private int status_;
  /**
   * <pre>
   **
   * 状态(0:有效， 1：锁定， 2：禁用）
   * </pre>
   *
   * <code>int32 status = 15;</code>
   */
  public int getStatus() {
    return status_;
  }

  public static final int CREATETIME_FIELD_NUMBER = 16;
  private long createTime_;
  /**
   * <pre>
   **
   * 创建时间
   * </pre>
   *
   * <code>int64 createTime = 16;</code>
   */
  public long getCreateTime() {
    return createTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (userId_ != 0L) {
      output.writeInt64(2, userId_);
    }
    if (dealId_ != 0L) {
      output.writeInt64(3, dealId_);
    }
    if (accountId_ != 0L) {
      output.writeInt64(4, accountId_);
    }
    if (tradeTime_ != 0L) {
      output.writeInt64(5, tradeTime_);
    }
    if (stockId_ != 0L) {
      output.writeInt64(6, stockId_);
    }
    if (!getStockCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, stockCode_);
    }
    if (!getCurrencyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, currency_);
    }
    if (direction_ != 0) {
      output.writeInt32(9, direction_);
    }
    if (tradeAmount_ != 0L) {
      output.writeInt64(10, tradeAmount_);
    }
    if (tradeVolume_ != 0L) {
      output.writeInt64(11, tradeVolume_);
    }
    if (tradePrice_ != 0L) {
      output.writeInt64(12, tradePrice_);
    }
    if (taxes_ != 0L) {
      output.writeInt64(13, taxes_);
    }
    if (commission_ != 0L) {
      output.writeInt64(14, commission_);
    }
    if (status_ != 0) {
      output.writeInt32(15, status_);
    }
    if (createTime_ != 0L) {
      output.writeInt64(16, createTime_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, userId_);
    }
    if (dealId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, dealId_);
    }
    if (accountId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, accountId_);
    }
    if (tradeTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, tradeTime_);
    }
    if (stockId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, stockId_);
    }
    if (!getStockCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, stockCode_);
    }
    if (!getCurrencyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, currency_);
    }
    if (direction_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, direction_);
    }
    if (tradeAmount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(10, tradeAmount_);
    }
    if (tradeVolume_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(11, tradeVolume_);
    }
    if (tradePrice_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(12, tradePrice_);
    }
    if (taxes_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(13, taxes_);
    }
    if (commission_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(14, commission_);
    }
    if (status_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(15, status_);
    }
    if (createTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(16, createTime_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle)) {
      return super.equals(obj);
    }
    com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle other = (com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle) obj;

    if (getId()
        != other.getId()) return false;
    if (getUserId()
        != other.getUserId()) return false;
    if (getDealId()
        != other.getDealId()) return false;
    if (getAccountId()
        != other.getAccountId()) return false;
    if (getTradeTime()
        != other.getTradeTime()) return false;
    if (getStockId()
        != other.getStockId()) return false;
    if (!getStockCode()
        .equals(other.getStockCode())) return false;
    if (!getCurrency()
        .equals(other.getCurrency())) return false;
    if (getDirection()
        != other.getDirection()) return false;
    if (getTradeAmount()
        != other.getTradeAmount()) return false;
    if (getTradeVolume()
        != other.getTradeVolume()) return false;
    if (getTradePrice()
        != other.getTradePrice()) return false;
    if (getTaxes()
        != other.getTaxes()) return false;
    if (getCommission()
        != other.getCommission()) return false;
    if (getStatus()
        != other.getStatus()) return false;
    if (getCreateTime()
        != other.getCreateTime()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserId());
    hash = (37 * hash) + DEALID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDealId());
    hash = (37 * hash) + ACCOUNTID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAccountId());
    hash = (37 * hash) + TRADETIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTradeTime());
    hash = (37 * hash) + STOCKID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStockId());
    hash = (37 * hash) + STOCKCODE_FIELD_NUMBER;
    hash = (53 * hash) + getStockCode().hashCode();
    hash = (37 * hash) + CURRENCY_FIELD_NUMBER;
    hash = (53 * hash) + getCurrency().hashCode();
    hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
    hash = (53 * hash) + getDirection();
    hash = (37 * hash) + TRADEAMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTradeAmount());
    hash = (37 * hash) + TRADEVOLUME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTradeVolume());
    hash = (37 * hash) + TRADEPRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTradePrice());
    hash = (37 * hash) + TAXES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTaxes());
    hash = (37 * hash) + COMMISSION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCommission());
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus();
    hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreateTime());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 获取账户交易单返回数据结构
   * </pre>
   *
   * Protobuf type {@code GetAccountSettlementSingle}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetAccountSettlementSingle)
      com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingleOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.itcast.bulls.stock.struct.grpc.trade.StockFinanceServiceProto.internal_static_GetAccountSettlementSingle_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.itcast.bulls.stock.struct.grpc.trade.StockFinanceServiceProto.internal_static_GetAccountSettlementSingle_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle.class, com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle.Builder.class);
    }

    // Construct using com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      userId_ = 0L;

      dealId_ = 0L;

      accountId_ = 0L;

      tradeTime_ = 0L;

      stockId_ = 0L;

      stockCode_ = "";

      currency_ = "";

      direction_ = 0;

      tradeAmount_ = 0L;

      tradeVolume_ = 0L;

      tradePrice_ = 0L;

      taxes_ = 0L;

      commission_ = 0L;

      status_ = 0;

      createTime_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.itcast.bulls.stock.struct.grpc.trade.StockFinanceServiceProto.internal_static_GetAccountSettlementSingle_descriptor;
    }

    @java.lang.Override
    public com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle getDefaultInstanceForType() {
      return com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle.getDefaultInstance();
    }

    @java.lang.Override
    public com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle build() {
      com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle buildPartial() {
      com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle result = new com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle(this);
      result.id_ = id_;
      result.userId_ = userId_;
      result.dealId_ = dealId_;
      result.accountId_ = accountId_;
      result.tradeTime_ = tradeTime_;
      result.stockId_ = stockId_;
      result.stockCode_ = stockCode_;
      result.currency_ = currency_;
      result.direction_ = direction_;
      result.tradeAmount_ = tradeAmount_;
      result.tradeVolume_ = tradeVolume_;
      result.tradePrice_ = tradePrice_;
      result.taxes_ = taxes_;
      result.commission_ = commission_;
      result.status_ = status_;
      result.createTime_ = createTime_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle) {
        return mergeFrom((com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle other) {
      if (other == com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      if (other.getDealId() != 0L) {
        setDealId(other.getDealId());
      }
      if (other.getAccountId() != 0L) {
        setAccountId(other.getAccountId());
      }
      if (other.getTradeTime() != 0L) {
        setTradeTime(other.getTradeTime());
      }
      if (other.getStockId() != 0L) {
        setStockId(other.getStockId());
      }
      if (!other.getStockCode().isEmpty()) {
        stockCode_ = other.stockCode_;
        onChanged();
      }
      if (!other.getCurrency().isEmpty()) {
        currency_ = other.currency_;
        onChanged();
      }
      if (other.getDirection() != 0) {
        setDirection(other.getDirection());
      }
      if (other.getTradeAmount() != 0L) {
        setTradeAmount(other.getTradeAmount());
      }
      if (other.getTradeVolume() != 0L) {
        setTradeVolume(other.getTradeVolume());
      }
      if (other.getTradePrice() != 0L) {
        setTradePrice(other.getTradePrice());
      }
      if (other.getTaxes() != 0L) {
        setTaxes(other.getTaxes());
      }
      if (other.getCommission() != 0L) {
        setCommission(other.getCommission());
      }
      if (other.getStatus() != 0) {
        setStatus(other.getStatus());
      }
      if (other.getCreateTime() != 0L) {
        setCreateTime(other.getCreateTime());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <pre>
     **
     * 主键标识
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <pre>
     **
     * 主键标识
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 主键标识
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private long userId_ ;
    /**
     * <pre>
     **
     * 用户ID
     * </pre>
     *
     * <code>int64 userId = 2;</code>
     */
    public long getUserId() {
      return userId_;
    }
    /**
     * <pre>
     **
     * 用户ID
     * </pre>
     *
     * <code>int64 userId = 2;</code>
     */
    public Builder setUserId(long value) {
      
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 用户ID
     * </pre>
     *
     * <code>int64 userId = 2;</code>
     */
    public Builder clearUserId() {
      
      userId_ = 0L;
      onChanged();
      return this;
    }

    private long dealId_ ;
    /**
     * <pre>
     **
     * 成交记录ID
     * </pre>
     *
     * <code>int64 dealId = 3;</code>
     */
    public long getDealId() {
      return dealId_;
    }
    /**
     * <pre>
     **
     * 成交记录ID
     * </pre>
     *
     * <code>int64 dealId = 3;</code>
     */
    public Builder setDealId(long value) {
      
      dealId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 成交记录ID
     * </pre>
     *
     * <code>int64 dealId = 3;</code>
     */
    public Builder clearDealId() {
      
      dealId_ = 0L;
      onChanged();
      return this;
    }

    private long accountId_ ;
    /**
     * <pre>
     **
     * 交易账号ID
     * </pre>
     *
     * <code>int64 accountId = 4;</code>
     */
    public long getAccountId() {
      return accountId_;
    }
    /**
     * <pre>
     **
     * 交易账号ID
     * </pre>
     *
     * <code>int64 accountId = 4;</code>
     */
    public Builder setAccountId(long value) {
      
      accountId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 交易账号ID
     * </pre>
     *
     * <code>int64 accountId = 4;</code>
     */
    public Builder clearAccountId() {
      
      accountId_ = 0L;
      onChanged();
      return this;
    }

    private long tradeTime_ ;
    /**
     * <pre>
     **
     * 交易时间
     * </pre>
     *
     * <code>int64 tradeTime = 5;</code>
     */
    public long getTradeTime() {
      return tradeTime_;
    }
    /**
     * <pre>
     **
     * 交易时间
     * </pre>
     *
     * <code>int64 tradeTime = 5;</code>
     */
    public Builder setTradeTime(long value) {
      
      tradeTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 交易时间
     * </pre>
     *
     * <code>int64 tradeTime = 5;</code>
     */
    public Builder clearTradeTime() {
      
      tradeTime_ = 0L;
      onChanged();
      return this;
    }

    private long stockId_ ;
    /**
     * <pre>
     **
     * 股票ID
     * </pre>
     *
     * <code>int64 stockId = 6;</code>
     */
    public long getStockId() {
      return stockId_;
    }
    /**
     * <pre>
     **
     * 股票ID
     * </pre>
     *
     * <code>int64 stockId = 6;</code>
     */
    public Builder setStockId(long value) {
      
      stockId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 股票ID
     * </pre>
     *
     * <code>int64 stockId = 6;</code>
     */
    public Builder clearStockId() {
      
      stockId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object stockCode_ = "";
    /**
     * <pre>
     **
     * 股票代码
     * </pre>
     *
     * <code>string stockCode = 7;</code>
     */
    public java.lang.String getStockCode() {
      java.lang.Object ref = stockCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stockCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **
     * 股票代码
     * </pre>
     *
     * <code>string stockCode = 7;</code>
     */
    public com.google.protobuf.ByteString
        getStockCodeBytes() {
      java.lang.Object ref = stockCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stockCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **
     * 股票代码
     * </pre>
     *
     * <code>string stockCode = 7;</code>
     */
    public Builder setStockCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      stockCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 股票代码
     * </pre>
     *
     * <code>string stockCode = 7;</code>
     */
    public Builder clearStockCode() {
      
      stockCode_ = getDefaultInstance().getStockCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 股票代码
     * </pre>
     *
     * <code>string stockCode = 7;</code>
     */
    public Builder setStockCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      stockCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object currency_ = "";
    /**
     * <pre>
     **
     * 币种
     * </pre>
     *
     * <code>string currency = 8;</code>
     */
    public java.lang.String getCurrency() {
      java.lang.Object ref = currency_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currency_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **
     * 币种
     * </pre>
     *
     * <code>string currency = 8;</code>
     */
    public com.google.protobuf.ByteString
        getCurrencyBytes() {
      java.lang.Object ref = currency_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **
     * 币种
     * </pre>
     *
     * <code>string currency = 8;</code>
     */
    public Builder setCurrency(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      currency_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 币种
     * </pre>
     *
     * <code>string currency = 8;</code>
     */
    public Builder clearCurrency() {
      
      currency_ = getDefaultInstance().getCurrency();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 币种
     * </pre>
     *
     * <code>string currency = 8;</code>
     */
    public Builder setCurrencyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      currency_ = value;
      onChanged();
      return this;
    }

    private int direction_ ;
    /**
     * <pre>
     **
     * 买卖方向
     * </pre>
     *
     * <code>int32 direction = 9;</code>
     */
    public int getDirection() {
      return direction_;
    }
    /**
     * <pre>
     **
     * 买卖方向
     * </pre>
     *
     * <code>int32 direction = 9;</code>
     */
    public Builder setDirection(int value) {
      
      direction_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 买卖方向
     * </pre>
     *
     * <code>int32 direction = 9;</code>
     */
    public Builder clearDirection() {
      
      direction_ = 0;
      onChanged();
      return this;
    }

    private long tradeAmount_ ;
    /**
     * <pre>
     **
     * 交易金额
     * </pre>
     *
     * <code>int64 tradeAmount = 10;</code>
     */
    public long getTradeAmount() {
      return tradeAmount_;
    }
    /**
     * <pre>
     **
     * 交易金额
     * </pre>
     *
     * <code>int64 tradeAmount = 10;</code>
     */
    public Builder setTradeAmount(long value) {
      
      tradeAmount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 交易金额
     * </pre>
     *
     * <code>int64 tradeAmount = 10;</code>
     */
    public Builder clearTradeAmount() {
      
      tradeAmount_ = 0L;
      onChanged();
      return this;
    }

    private long tradeVolume_ ;
    /**
     * <pre>
     **
     * 交易数量
     * </pre>
     *
     * <code>int64 tradeVolume = 11;</code>
     */
    public long getTradeVolume() {
      return tradeVolume_;
    }
    /**
     * <pre>
     **
     * 交易数量
     * </pre>
     *
     * <code>int64 tradeVolume = 11;</code>
     */
    public Builder setTradeVolume(long value) {
      
      tradeVolume_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 交易数量
     * </pre>
     *
     * <code>int64 tradeVolume = 11;</code>
     */
    public Builder clearTradeVolume() {
      
      tradeVolume_ = 0L;
      onChanged();
      return this;
    }

    private long tradePrice_ ;
    /**
     * <pre>
     **
     * 交易价格
     * </pre>
     *
     * <code>int64 tradePrice = 12;</code>
     */
    public long getTradePrice() {
      return tradePrice_;
    }
    /**
     * <pre>
     **
     * 交易价格
     * </pre>
     *
     * <code>int64 tradePrice = 12;</code>
     */
    public Builder setTradePrice(long value) {
      
      tradePrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 交易价格
     * </pre>
     *
     * <code>int64 tradePrice = 12;</code>
     */
    public Builder clearTradePrice() {
      
      tradePrice_ = 0L;
      onChanged();
      return this;
    }

    private long taxes_ ;
    /**
     * <pre>
     **
     * 税费（印花税+过户费+交易规费）
     * </pre>
     *
     * <code>int64 taxes = 13;</code>
     */
    public long getTaxes() {
      return taxes_;
    }
    /**
     * <pre>
     **
     * 税费（印花税+过户费+交易规费）
     * </pre>
     *
     * <code>int64 taxes = 13;</code>
     */
    public Builder setTaxes(long value) {
      
      taxes_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 税费（印花税+过户费+交易规费）
     * </pre>
     *
     * <code>int64 taxes = 13;</code>
     */
    public Builder clearTaxes() {
      
      taxes_ = 0L;
      onChanged();
      return this;
    }

    private long commission_ ;
    /**
     * <pre>
     **
     * 佣金
     * </pre>
     *
     * <code>int64 commission = 14;</code>
     */
    public long getCommission() {
      return commission_;
    }
    /**
     * <pre>
     **
     * 佣金
     * </pre>
     *
     * <code>int64 commission = 14;</code>
     */
    public Builder setCommission(long value) {
      
      commission_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 佣金
     * </pre>
     *
     * <code>int64 commission = 14;</code>
     */
    public Builder clearCommission() {
      
      commission_ = 0L;
      onChanged();
      return this;
    }

    private int status_ ;
    /**
     * <pre>
     **
     * 状态(0:有效， 1：锁定， 2：禁用）
     * </pre>
     *
     * <code>int32 status = 15;</code>
     */
    public int getStatus() {
      return status_;
    }
    /**
     * <pre>
     **
     * 状态(0:有效， 1：锁定， 2：禁用）
     * </pre>
     *
     * <code>int32 status = 15;</code>
     */
    public Builder setStatus(int value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 状态(0:有效， 1：锁定， 2：禁用）
     * </pre>
     *
     * <code>int32 status = 15;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private long createTime_ ;
    /**
     * <pre>
     **
     * 创建时间
     * </pre>
     *
     * <code>int64 createTime = 16;</code>
     */
    public long getCreateTime() {
      return createTime_;
    }
    /**
     * <pre>
     **
     * 创建时间
     * </pre>
     *
     * <code>int64 createTime = 16;</code>
     */
    public Builder setCreateTime(long value) {
      
      createTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 创建时间
     * </pre>
     *
     * <code>int64 createTime = 16;</code>
     */
    public Builder clearCreateTime() {
      
      createTime_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetAccountSettlementSingle)
  }

  // @@protoc_insertion_point(class_scope:GetAccountSettlementSingle)
  private static final com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle();
  }

  public static com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetAccountSettlementSingle>
      PARSER = new com.google.protobuf.AbstractParser<GetAccountSettlementSingle>() {
    @java.lang.Override
    public GetAccountSettlementSingle parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetAccountSettlementSingle(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetAccountSettlementSingle> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetAccountSettlementSingle> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.itcast.bulls.stock.struct.grpc.trade.GetAccountSettlementSingle getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

