// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/StockPositionService.proto

package com.itcast.bulls.stock.struct.grpc.trade;

public interface GetAllPositionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllPositionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 账户ID
   * </pre>
   *
   * <code>int64 accountId = 1;</code>
   */
  long getAccountId();
}
