// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/StockFinanceService.proto

package com.itcast.bulls.stock.struct.grpc.trade;

public interface GetAccountSettlementRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAccountSettlementRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 accountId = 1;</code>
   */
  long getAccountId();

  /**
   * <code>int64 timeStart = 2;</code>
   */
  long getTimeStart();

  /**
   * <code>int64 timeEnd = 3;</code>
   */
  long getTimeEnd();
}
