// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/StockPositionService.proto

package com.itcast.bulls.stock.struct.grpc.trade;

public interface GetAllPositionReponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllPositionReponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>repeated .GetAllPositionData getAllPositionData = 3;</code>
   */
  java.util.List<com.itcast.bulls.stock.struct.grpc.trade.GetAllPositionData> 
      getGetAllPositionDataList();
  /**
   * <code>repeated .GetAllPositionData getAllPositionData = 3;</code>
   */
  com.itcast.bulls.stock.struct.grpc.trade.GetAllPositionData getGetAllPositionData(int index);
  /**
   * <code>repeated .GetAllPositionData getAllPositionData = 3;</code>
   */
  int getGetAllPositionDataCount();
  /**
   * <code>repeated .GetAllPositionData getAllPositionData = 3;</code>
   */
  java.util.List<? extends com.itcast.bulls.stock.struct.grpc.trade.GetAllPositionDataOrBuilder> 
      getGetAllPositionDataOrBuilderList();
  /**
   * <code>repeated .GetAllPositionData getAllPositionData = 3;</code>
   */
  com.itcast.bulls.stock.struct.grpc.trade.GetAllPositionDataOrBuilder getGetAllPositionDataOrBuilder(
      int index);
}
