// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/StockTradeDealService.proto

package com.itcast.bulls.stock.struct.grpc.trade;

public interface GetOrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetOrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 accountId = 1;</code>
   */
  long getAccountId();

  /**
   * <code>int64 orderId = 2;</code>
   */
  long getOrderId();
}
