// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/StockPendingService.proto

package com.itcast.bulls.stock.struct.grpc.trade;

public interface LimitPlaceOrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LimitPlaceOrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 交易账户ID
   * </pre>
   *
   * <code>int64 accountId = 1;</code>
   */
  long getAccountId();

  /**
   * <pre>
   * 股票产品ID
   * </pre>
   *
   * <code>int64 stockId = 2;</code>
   */
  long getStockId();

  /**
   * <pre>
   * 买卖方向
   * </pre>
   *
   * <code>int32 direction = 3;</code>
   */
  int getDirection();

  /**
   * <pre>
   * 下单类型
   * </pre>
   *
   * <code>int32 type = 4;</code>
   */
  int getType();

  /**
   * <pre>
   * 请求数量
   * </pre>
   *
   * <code>int32 execVolume = 5;</code>
   */
  int getExecVolume();

  /**
   * <pre>
   * 请求价格
   * </pre>
   *
   * <code>int64 execPrice = 6;</code>
   */
  long getExecPrice();
}
