// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/StockUserService.proto

package com.itcast.bulls.stock.struct.grpc.trade;

public interface LoginReponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LoginReponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>int64 userId = 3;</code>
   */
  long getUserId();

  /**
   * <code>int64 accountId = 4;</code>
   */
  long getAccountId();
}
