// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/StockTradeDealService.proto

package com.itcast.bulls.stock.struct.grpc.trade;

public interface PlaceOrderReponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PlaceOrderReponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>int64 orderId = 3;</code>
   */
  long getOrderId();

  /**
   * <code>int64 dealId = 4;</code>
   */
  long getDealId();

  /**
   * <code>int32 execVolume = 5;</code>
   */
  int getExecVolume();

  /**
   * <code>int64 execPrice = 6;</code>
   */
  long getExecPrice();
}
