// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/StockPendingService.proto

package com.itcast.bulls.stock.struct.grpc.trade;

public final class StockPendingServiceProto {
  private StockPendingServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LimitPlaceOrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LimitPlaceOrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LimitPlaceOrderReponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LimitPlaceOrderReponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RecallOrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RecallOrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RecallOrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RecallOrderResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036grpc/StockPendingService.proto\"\204\001\n\026Lim" +
      "itPlaceOrderRequest\022\021\n\taccountId\030\001 \001(\003\022\017" +
      "\n\007stockId\030\002 \001(\003\022\021\n\tdirection\030\003 \001(\005\022\014\n\004ty" +
      "pe\030\004 \001(\005\022\022\n\nexecVolume\030\005 \001(\005\022\021\n\texecPric" +
      "e\030\006 \001(\003\"J\n\026LimitPlaceOrderReponse\022\016\n\006sta" +
      "tus\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\022\017\n\007orderId\030\003 " +
      "\001(\003\"I\n\022RecallOrderRequest\022\021\n\taccountId\030\001" +
      " \001(\003\022\017\n\007orderId\030\002 \001(\003\022\017\n\007stockId\030\003 \001(\003\"6" +
      "\n\023RecallOrderResponse\022\016\n\006status\030\001 \001(\t\022\017\n" +
      "\007message\030\002 \001(\t2\230\001\n\023StockPendingService\022E" +
      "\n\017limitPlaceOrder\022\027.LimitPlaceOrderReque" +
      "st\032\027.LimitPlaceOrderReponse\"\000\022:\n\013recallO" +
      "rder\022\023.RecallOrderRequest\032\024.RecallOrderR" +
      "esponse\"\000BF\n(com.itcast.bulls.stock.stru" +
      "ct.grpc.tradeB\030StockPendingServiceProtoP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_LimitPlaceOrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LimitPlaceOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LimitPlaceOrderRequest_descriptor,
        new java.lang.String[] { "AccountId", "StockId", "Direction", "Type", "ExecVolume", "ExecPrice", });
    internal_static_LimitPlaceOrderReponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LimitPlaceOrderReponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LimitPlaceOrderReponse_descriptor,
        new java.lang.String[] { "Status", "Message", "OrderId", });
    internal_static_RecallOrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_RecallOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RecallOrderRequest_descriptor,
        new java.lang.String[] { "AccountId", "OrderId", "StockId", });
    internal_static_RecallOrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_RecallOrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RecallOrderResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
