// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockMessage.proto

package com.itcast.bulls.stock.struct.netty.trade;

public interface AccountWarnSettingDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AccountWarnSettingData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 股票产品ID
   * </pre>
   *
   * <code>int64 stockId = 1;</code>
   */
  long getStockId();

  /**
   * <pre>
   * 预警类型 (0: 止损, 1:止盈)
   * </pre>
   *
   * <code>int32 warnType = 2;</code>
   */
  int getWarnType();

  /**
   * <pre>
   * 止盈止损设置比例(单位：%， 例2.28 代表02.28%)
   * </pre>
   *
   * <code>double stopRate = 3;</code>
   */
  double getStopRate();

  /**
   * <pre>
   * 通知方式(APP:站内信，EMAIL：邮件，SMS：短信， 多个以逗号分隔)
   * </pre>
   *
   * <code>string notifyType = 4;</code>
   */
  java.lang.String getNotifyType();
  /**
   * <pre>
   * 通知方式(APP:站内信，EMAIL：邮件，SMS：短信， 多个以逗号分隔)
   * </pre>
   *
   * <code>string notifyType = 4;</code>
   */
  com.google.protobuf.ByteString
      getNotifyTypeBytes();
}
