// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockMessage.proto

package com.itcast.bulls.stock.struct.netty.trade;

public interface AccountWarnSettingRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AccountWarnSettingResp)
    com.google.protobuf.MessageOrBuilder {
}
