// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockMessage.proto

package com.itcast.bulls.stock.struct.netty.trade;

/**
 * <pre>
 * 获取所有仓位返回数据集合
 * </pre>
 *
 * Protobuf type {@code GetAllPositionList}
 */
public  final class GetAllPositionList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetAllPositionList)
    GetAllPositionListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetAllPositionList.newBuilder() to construct.
  private GetAllPositionList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetAllPositionList() {
    getAllPositionData_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetAllPositionList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetAllPositionList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              getAllPositionData_ = new java.util.ArrayList<com.itcast.bulls.stock.struct.netty.trade.GetAllPositionData>();
              mutable_bitField0_ |= 0x00000001;
            }
            getAllPositionData_.add(
                input.readMessage(com.itcast.bulls.stock.struct.netty.trade.GetAllPositionData.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        getAllPositionData_ = java.util.Collections.unmodifiableList(getAllPositionData_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.itcast.bulls.stock.struct.netty.trade.StockMessageProto.internal_static_GetAllPositionList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.itcast.bulls.stock.struct.netty.trade.StockMessageProto.internal_static_GetAllPositionList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList.class, com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList.Builder.class);
  }

  public static final int GETALLPOSITIONDATA_FIELD_NUMBER = 1;
  private java.util.List<com.itcast.bulls.stock.struct.netty.trade.GetAllPositionData> getAllPositionData_;
  /**
   * <code>repeated .GetAllPositionData getAllPositionData = 1;</code>
   */
  public java.util.List<com.itcast.bulls.stock.struct.netty.trade.GetAllPositionData> getGetAllPositionDataList() {
    return getAllPositionData_;
  }
  /**
   * <code>repeated .GetAllPositionData getAllPositionData = 1;</code>
   */
  public java.util.List<? extends com.itcast.bulls.stock.struct.netty.trade.GetAllPositionDataOrBuilder> 
      getGetAllPositionDataOrBuilderList() {
    return getAllPositionData_;
  }
  /**
   * <code>repeated .GetAllPositionData getAllPositionData = 1;</code>
   */
  public int getGetAllPositionDataCount() {
    return getAllPositionData_.size();
  }
  /**
   * <code>repeated .GetAllPositionData getAllPositionData = 1;</code>
   */
  public com.itcast.bulls.stock.struct.netty.trade.GetAllPositionData getGetAllPositionData(int index) {
    return getAllPositionData_.get(index);
  }
  /**
   * <code>repeated .GetAllPositionData getAllPositionData = 1;</code>
   */
  public com.itcast.bulls.stock.struct.netty.trade.GetAllPositionDataOrBuilder getGetAllPositionDataOrBuilder(
      int index) {
    return getAllPositionData_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < getAllPositionData_.size(); i++) {
      output.writeMessage(1, getAllPositionData_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < getAllPositionData_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getAllPositionData_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList)) {
      return super.equals(obj);
    }
    com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList other = (com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList) obj;

    if (!getGetAllPositionDataList()
        .equals(other.getGetAllPositionDataList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getGetAllPositionDataCount() > 0) {
      hash = (37 * hash) + GETALLPOSITIONDATA_FIELD_NUMBER;
      hash = (53 * hash) + getGetAllPositionDataList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 获取所有仓位返回数据集合
   * </pre>
   *
   * Protobuf type {@code GetAllPositionList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetAllPositionList)
      com.itcast.bulls.stock.struct.netty.trade.GetAllPositionListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.itcast.bulls.stock.struct.netty.trade.StockMessageProto.internal_static_GetAllPositionList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.itcast.bulls.stock.struct.netty.trade.StockMessageProto.internal_static_GetAllPositionList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList.class, com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList.Builder.class);
    }

    // Construct using com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getGetAllPositionDataFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (getAllPositionDataBuilder_ == null) {
        getAllPositionData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        getAllPositionDataBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.itcast.bulls.stock.struct.netty.trade.StockMessageProto.internal_static_GetAllPositionList_descriptor;
    }

    @java.lang.Override
    public com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList getDefaultInstanceForType() {
      return com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList.getDefaultInstance();
    }

    @java.lang.Override
    public com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList build() {
      com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList buildPartial() {
      com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList result = new com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList(this);
      int from_bitField0_ = bitField0_;
      if (getAllPositionDataBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          getAllPositionData_ = java.util.Collections.unmodifiableList(getAllPositionData_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.getAllPositionData_ = getAllPositionData_;
      } else {
        result.getAllPositionData_ = getAllPositionDataBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList) {
        return mergeFrom((com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList other) {
      if (other == com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList.getDefaultInstance()) return this;
      if (getAllPositionDataBuilder_ == null) {
        if (!other.getAllPositionData_.isEmpty()) {
          if (getAllPositionData_.isEmpty()) {
            getAllPositionData_ = other.getAllPositionData_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureGetAllPositionDataIsMutable();
            getAllPositionData_.addAll(other.getAllPositionData_);
          }
          onChanged();
        }
      } else {
        if (!other.getAllPositionData_.isEmpty()) {
          if (getAllPositionDataBuilder_.isEmpty()) {
            getAllPositionDataBuilder_.dispose();
            getAllPositionDataBuilder_ = null;
            getAllPositionData_ = other.getAllPositionData_;
            bitField0_ = (bitField0_ & ~0x00000001);
            getAllPositionDataBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getGetAllPositionDataFieldBuilder() : null;
          } else {
            getAllPositionDataBuilder_.addAllMessages(other.getAllPositionData_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.itcast.bulls.stock.struct.netty.trade.GetAllPositionData> getAllPositionData_ =
      java.util.Collections.emptyList();
    private void ensureGetAllPositionDataIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        getAllPositionData_ = new java.util.ArrayList<com.itcast.bulls.stock.struct.netty.trade.GetAllPositionData>(getAllPositionData_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.itcast.bulls.stock.struct.netty.trade.GetAllPositionData, com.itcast.bulls.stock.struct.netty.trade.GetAllPositionData.Builder, com.itcast.bulls.stock.struct.netty.trade.GetAllPositionDataOrBuilder> getAllPositionDataBuilder_;

    /**
     * <code>repeated .GetAllPositionData getAllPositionData = 1;</code>
     */
    public java.util.List<com.itcast.bulls.stock.struct.netty.trade.GetAllPositionData> getGetAllPositionDataList() {
      if (getAllPositionDataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(getAllPositionData_);
      } else {
        return getAllPositionDataBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .GetAllPositionData getAllPositionData = 1;</code>
     */
    public int getGetAllPositionDataCount() {
      if (getAllPositionDataBuilder_ == null) {
        return getAllPositionData_.size();
      } else {
        return getAllPositionDataBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .GetAllPositionData getAllPositionData = 1;</code>
     */
    public com.itcast.bulls.stock.struct.netty.trade.GetAllPositionData getGetAllPositionData(int index) {
      if (getAllPositionDataBuilder_ == null) {
        return getAllPositionData_.get(index);
      } else {
        return getAllPositionDataBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .GetAllPositionData getAllPositionData = 1;</code>
     */
    public Builder setGetAllPositionData(
        int index, com.itcast.bulls.stock.struct.netty.trade.GetAllPositionData value) {
      if (getAllPositionDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGetAllPositionDataIsMutable();
        getAllPositionData_.set(index, value);
        onChanged();
      } else {
        getAllPositionDataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GetAllPositionData getAllPositionData = 1;</code>
     */
    public Builder setGetAllPositionData(
        int index, com.itcast.bulls.stock.struct.netty.trade.GetAllPositionData.Builder builderForValue) {
      if (getAllPositionDataBuilder_ == null) {
        ensureGetAllPositionDataIsMutable();
        getAllPositionData_.set(index, builderForValue.build());
        onChanged();
      } else {
        getAllPositionDataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GetAllPositionData getAllPositionData = 1;</code>
     */
    public Builder addGetAllPositionData(com.itcast.bulls.stock.struct.netty.trade.GetAllPositionData value) {
      if (getAllPositionDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGetAllPositionDataIsMutable();
        getAllPositionData_.add(value);
        onChanged();
      } else {
        getAllPositionDataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .GetAllPositionData getAllPositionData = 1;</code>
     */
    public Builder addGetAllPositionData(
        int index, com.itcast.bulls.stock.struct.netty.trade.GetAllPositionData value) {
      if (getAllPositionDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGetAllPositionDataIsMutable();
        getAllPositionData_.add(index, value);
        onChanged();
      } else {
        getAllPositionDataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GetAllPositionData getAllPositionData = 1;</code>
     */
    public Builder addGetAllPositionData(
        com.itcast.bulls.stock.struct.netty.trade.GetAllPositionData.Builder builderForValue) {
      if (getAllPositionDataBuilder_ == null) {
        ensureGetAllPositionDataIsMutable();
        getAllPositionData_.add(builderForValue.build());
        onChanged();
      } else {
        getAllPositionDataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GetAllPositionData getAllPositionData = 1;</code>
     */
    public Builder addGetAllPositionData(
        int index, com.itcast.bulls.stock.struct.netty.trade.GetAllPositionData.Builder builderForValue) {
      if (getAllPositionDataBuilder_ == null) {
        ensureGetAllPositionDataIsMutable();
        getAllPositionData_.add(index, builderForValue.build());
        onChanged();
      } else {
        getAllPositionDataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GetAllPositionData getAllPositionData = 1;</code>
     */
    public Builder addAllGetAllPositionData(
        java.lang.Iterable<? extends com.itcast.bulls.stock.struct.netty.trade.GetAllPositionData> values) {
      if (getAllPositionDataBuilder_ == null) {
        ensureGetAllPositionDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, getAllPositionData_);
        onChanged();
      } else {
        getAllPositionDataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .GetAllPositionData getAllPositionData = 1;</code>
     */
    public Builder clearGetAllPositionData() {
      if (getAllPositionDataBuilder_ == null) {
        getAllPositionData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        getAllPositionDataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .GetAllPositionData getAllPositionData = 1;</code>
     */
    public Builder removeGetAllPositionData(int index) {
      if (getAllPositionDataBuilder_ == null) {
        ensureGetAllPositionDataIsMutable();
        getAllPositionData_.remove(index);
        onChanged();
      } else {
        getAllPositionDataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .GetAllPositionData getAllPositionData = 1;</code>
     */
    public com.itcast.bulls.stock.struct.netty.trade.GetAllPositionData.Builder getGetAllPositionDataBuilder(
        int index) {
      return getGetAllPositionDataFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .GetAllPositionData getAllPositionData = 1;</code>
     */
    public com.itcast.bulls.stock.struct.netty.trade.GetAllPositionDataOrBuilder getGetAllPositionDataOrBuilder(
        int index) {
      if (getAllPositionDataBuilder_ == null) {
        return getAllPositionData_.get(index);  } else {
        return getAllPositionDataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .GetAllPositionData getAllPositionData = 1;</code>
     */
    public java.util.List<? extends com.itcast.bulls.stock.struct.netty.trade.GetAllPositionDataOrBuilder> 
         getGetAllPositionDataOrBuilderList() {
      if (getAllPositionDataBuilder_ != null) {
        return getAllPositionDataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(getAllPositionData_);
      }
    }
    /**
     * <code>repeated .GetAllPositionData getAllPositionData = 1;</code>
     */
    public com.itcast.bulls.stock.struct.netty.trade.GetAllPositionData.Builder addGetAllPositionDataBuilder() {
      return getGetAllPositionDataFieldBuilder().addBuilder(
          com.itcast.bulls.stock.struct.netty.trade.GetAllPositionData.getDefaultInstance());
    }
    /**
     * <code>repeated .GetAllPositionData getAllPositionData = 1;</code>
     */
    public com.itcast.bulls.stock.struct.netty.trade.GetAllPositionData.Builder addGetAllPositionDataBuilder(
        int index) {
      return getGetAllPositionDataFieldBuilder().addBuilder(
          index, com.itcast.bulls.stock.struct.netty.trade.GetAllPositionData.getDefaultInstance());
    }
    /**
     * <code>repeated .GetAllPositionData getAllPositionData = 1;</code>
     */
    public java.util.List<com.itcast.bulls.stock.struct.netty.trade.GetAllPositionData.Builder> 
         getGetAllPositionDataBuilderList() {
      return getGetAllPositionDataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.itcast.bulls.stock.struct.netty.trade.GetAllPositionData, com.itcast.bulls.stock.struct.netty.trade.GetAllPositionData.Builder, com.itcast.bulls.stock.struct.netty.trade.GetAllPositionDataOrBuilder> 
        getGetAllPositionDataFieldBuilder() {
      if (getAllPositionDataBuilder_ == null) {
        getAllPositionDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.itcast.bulls.stock.struct.netty.trade.GetAllPositionData, com.itcast.bulls.stock.struct.netty.trade.GetAllPositionData.Builder, com.itcast.bulls.stock.struct.netty.trade.GetAllPositionDataOrBuilder>(
                getAllPositionData_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        getAllPositionData_ = null;
      }
      return getAllPositionDataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetAllPositionList)
  }

  // @@protoc_insertion_point(class_scope:GetAllPositionList)
  private static final com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList();
  }

  public static com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetAllPositionList>
      PARSER = new com.google.protobuf.AbstractParser<GetAllPositionList>() {
    @java.lang.Override
    public GetAllPositionList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetAllPositionList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetAllPositionList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetAllPositionList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.itcast.bulls.stock.struct.netty.trade.GetAllPositionList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

