// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockMessage.proto

package com.itcast.bulls.stock.struct.netty.trade;

public interface GetAllPositionListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllPositionList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .GetAllPositionData getAllPositionData = 1;</code>
   */
  java.util.List<com.itcast.bulls.stock.struct.netty.trade.GetAllPositionData> 
      getGetAllPositionDataList();
  /**
   * <code>repeated .GetAllPositionData getAllPositionData = 1;</code>
   */
  com.itcast.bulls.stock.struct.netty.trade.GetAllPositionData getGetAllPositionData(int index);
  /**
   * <code>repeated .GetAllPositionData getAllPositionData = 1;</code>
   */
  int getGetAllPositionDataCount();
  /**
   * <code>repeated .GetAllPositionData getAllPositionData = 1;</code>
   */
  java.util.List<? extends com.itcast.bulls.stock.struct.netty.trade.GetAllPositionDataOrBuilder> 
      getGetAllPositionDataOrBuilderList();
  /**
   * <code>repeated .GetAllPositionData getAllPositionData = 1;</code>
   */
  com.itcast.bulls.stock.struct.netty.trade.GetAllPositionDataOrBuilder getGetAllPositionDataOrBuilder(
      int index);
}
