// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockMessage.proto

package com.itcast.bulls.stock.struct.netty.trade;

public interface GetAccountSettlementDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAccountSettlementData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 结束时间
   * </pre>
   *
   * <code>int64 timeStart = 1;</code>
   */
  long getTimeStart();

  /**
   * <pre>
   * 开始时间
   * </pre>
   *
   * <code>int64 timeEnd = 2;</code>
   */
  long getTimeEnd();
}
