// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockMessage.proto

package com.itcast.bulls.stock.struct.netty.trade;

public interface GetFinanceOverviewRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetFinanceOverviewResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 总资产
   * </pre>
   *
   * <code>int64 totalAssets = 1;</code>
   */
  long getTotalAssets();

  /**
   * <pre>
   * 总市值
   * </pre>
   *
   * <code>int64 totalMarketAmount = 2;</code>
   */
  long getTotalMarketAmount();

  /**
   * <pre>
   * 持仓盈亏
   * </pre>
   *
   * <code>int64 positionProfit = 3;</code>
   */
  long getPositionProfit();

  /**
   * <pre>
   * 当日持仓盈亏
   * </pre>
   *
   * <code>int64 dayProfit = 4;</code>
   */
  long getDayProfit();

  /**
   * <pre>
   * 账户余额
   * </pre>
   *
   * <code>int64 balance = 5;</code>
   */
  long getBalance();
}
