// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockMessage.proto

package com.itcast.bulls.stock.struct.netty.trade;

/**
 * <pre>
 * 资金总览返回数据结构
 * </pre>
 *
 * Protobuf type {@code GetFinanceOverviewResp}
 */
public  final class GetFinanceOverviewResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetFinanceOverviewResp)
    GetFinanceOverviewRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetFinanceOverviewResp.newBuilder() to construct.
  private GetFinanceOverviewResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetFinanceOverviewResp() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetFinanceOverviewResp();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetFinanceOverviewResp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            totalAssets_ = input.readInt64();
            break;
          }
          case 16: {

            totalMarketAmount_ = input.readInt64();
            break;
          }
          case 24: {

            positionProfit_ = input.readInt64();
            break;
          }
          case 32: {

            dayProfit_ = input.readInt64();
            break;
          }
          case 40: {

            balance_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.itcast.bulls.stock.struct.netty.trade.StockMessageProto.internal_static_GetFinanceOverviewResp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.itcast.bulls.stock.struct.netty.trade.StockMessageProto.internal_static_GetFinanceOverviewResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp.class, com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp.Builder.class);
  }

  public static final int TOTALASSETS_FIELD_NUMBER = 1;
  private long totalAssets_;
  /**
   * <pre>
   * 总资产
   * </pre>
   *
   * <code>int64 totalAssets = 1;</code>
   */
  public long getTotalAssets() {
    return totalAssets_;
  }

  public static final int TOTALMARKETAMOUNT_FIELD_NUMBER = 2;
  private long totalMarketAmount_;
  /**
   * <pre>
   * 总市值
   * </pre>
   *
   * <code>int64 totalMarketAmount = 2;</code>
   */
  public long getTotalMarketAmount() {
    return totalMarketAmount_;
  }

  public static final int POSITIONPROFIT_FIELD_NUMBER = 3;
  private long positionProfit_;
  /**
   * <pre>
   * 持仓盈亏
   * </pre>
   *
   * <code>int64 positionProfit = 3;</code>
   */
  public long getPositionProfit() {
    return positionProfit_;
  }

  public static final int DAYPROFIT_FIELD_NUMBER = 4;
  private long dayProfit_;
  /**
   * <pre>
   * 当日持仓盈亏
   * </pre>
   *
   * <code>int64 dayProfit = 4;</code>
   */
  public long getDayProfit() {
    return dayProfit_;
  }

  public static final int BALANCE_FIELD_NUMBER = 5;
  private long balance_;
  /**
   * <pre>
   * 账户余额
   * </pre>
   *
   * <code>int64 balance = 5;</code>
   */
  public long getBalance() {
    return balance_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (totalAssets_ != 0L) {
      output.writeInt64(1, totalAssets_);
    }
    if (totalMarketAmount_ != 0L) {
      output.writeInt64(2, totalMarketAmount_);
    }
    if (positionProfit_ != 0L) {
      output.writeInt64(3, positionProfit_);
    }
    if (dayProfit_ != 0L) {
      output.writeInt64(4, dayProfit_);
    }
    if (balance_ != 0L) {
      output.writeInt64(5, balance_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (totalAssets_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, totalAssets_);
    }
    if (totalMarketAmount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, totalMarketAmount_);
    }
    if (positionProfit_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, positionProfit_);
    }
    if (dayProfit_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, dayProfit_);
    }
    if (balance_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, balance_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp)) {
      return super.equals(obj);
    }
    com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp other = (com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp) obj;

    if (getTotalAssets()
        != other.getTotalAssets()) return false;
    if (getTotalMarketAmount()
        != other.getTotalMarketAmount()) return false;
    if (getPositionProfit()
        != other.getPositionProfit()) return false;
    if (getDayProfit()
        != other.getDayProfit()) return false;
    if (getBalance()
        != other.getBalance()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOTALASSETS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalAssets());
    hash = (37 * hash) + TOTALMARKETAMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalMarketAmount());
    hash = (37 * hash) + POSITIONPROFIT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPositionProfit());
    hash = (37 * hash) + DAYPROFIT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDayProfit());
    hash = (37 * hash) + BALANCE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBalance());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 资金总览返回数据结构
   * </pre>
   *
   * Protobuf type {@code GetFinanceOverviewResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetFinanceOverviewResp)
      com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.itcast.bulls.stock.struct.netty.trade.StockMessageProto.internal_static_GetFinanceOverviewResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.itcast.bulls.stock.struct.netty.trade.StockMessageProto.internal_static_GetFinanceOverviewResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp.class, com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp.Builder.class);
    }

    // Construct using com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      totalAssets_ = 0L;

      totalMarketAmount_ = 0L;

      positionProfit_ = 0L;

      dayProfit_ = 0L;

      balance_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.itcast.bulls.stock.struct.netty.trade.StockMessageProto.internal_static_GetFinanceOverviewResp_descriptor;
    }

    @java.lang.Override
    public com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp getDefaultInstanceForType() {
      return com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp.getDefaultInstance();
    }

    @java.lang.Override
    public com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp build() {
      com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp buildPartial() {
      com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp result = new com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp(this);
      result.totalAssets_ = totalAssets_;
      result.totalMarketAmount_ = totalMarketAmount_;
      result.positionProfit_ = positionProfit_;
      result.dayProfit_ = dayProfit_;
      result.balance_ = balance_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp) {
        return mergeFrom((com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp other) {
      if (other == com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp.getDefaultInstance()) return this;
      if (other.getTotalAssets() != 0L) {
        setTotalAssets(other.getTotalAssets());
      }
      if (other.getTotalMarketAmount() != 0L) {
        setTotalMarketAmount(other.getTotalMarketAmount());
      }
      if (other.getPositionProfit() != 0L) {
        setPositionProfit(other.getPositionProfit());
      }
      if (other.getDayProfit() != 0L) {
        setDayProfit(other.getDayProfit());
      }
      if (other.getBalance() != 0L) {
        setBalance(other.getBalance());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long totalAssets_ ;
    /**
     * <pre>
     * 总资产
     * </pre>
     *
     * <code>int64 totalAssets = 1;</code>
     */
    public long getTotalAssets() {
      return totalAssets_;
    }
    /**
     * <pre>
     * 总资产
     * </pre>
     *
     * <code>int64 totalAssets = 1;</code>
     */
    public Builder setTotalAssets(long value) {
      
      totalAssets_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 总资产
     * </pre>
     *
     * <code>int64 totalAssets = 1;</code>
     */
    public Builder clearTotalAssets() {
      
      totalAssets_ = 0L;
      onChanged();
      return this;
    }

    private long totalMarketAmount_ ;
    /**
     * <pre>
     * 总市值
     * </pre>
     *
     * <code>int64 totalMarketAmount = 2;</code>
     */
    public long getTotalMarketAmount() {
      return totalMarketAmount_;
    }
    /**
     * <pre>
     * 总市值
     * </pre>
     *
     * <code>int64 totalMarketAmount = 2;</code>
     */
    public Builder setTotalMarketAmount(long value) {
      
      totalMarketAmount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 总市值
     * </pre>
     *
     * <code>int64 totalMarketAmount = 2;</code>
     */
    public Builder clearTotalMarketAmount() {
      
      totalMarketAmount_ = 0L;
      onChanged();
      return this;
    }

    private long positionProfit_ ;
    /**
     * <pre>
     * 持仓盈亏
     * </pre>
     *
     * <code>int64 positionProfit = 3;</code>
     */
    public long getPositionProfit() {
      return positionProfit_;
    }
    /**
     * <pre>
     * 持仓盈亏
     * </pre>
     *
     * <code>int64 positionProfit = 3;</code>
     */
    public Builder setPositionProfit(long value) {
      
      positionProfit_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 持仓盈亏
     * </pre>
     *
     * <code>int64 positionProfit = 3;</code>
     */
    public Builder clearPositionProfit() {
      
      positionProfit_ = 0L;
      onChanged();
      return this;
    }

    private long dayProfit_ ;
    /**
     * <pre>
     * 当日持仓盈亏
     * </pre>
     *
     * <code>int64 dayProfit = 4;</code>
     */
    public long getDayProfit() {
      return dayProfit_;
    }
    /**
     * <pre>
     * 当日持仓盈亏
     * </pre>
     *
     * <code>int64 dayProfit = 4;</code>
     */
    public Builder setDayProfit(long value) {
      
      dayProfit_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 当日持仓盈亏
     * </pre>
     *
     * <code>int64 dayProfit = 4;</code>
     */
    public Builder clearDayProfit() {
      
      dayProfit_ = 0L;
      onChanged();
      return this;
    }

    private long balance_ ;
    /**
     * <pre>
     * 账户余额
     * </pre>
     *
     * <code>int64 balance = 5;</code>
     */
    public long getBalance() {
      return balance_;
    }
    /**
     * <pre>
     * 账户余额
     * </pre>
     *
     * <code>int64 balance = 5;</code>
     */
    public Builder setBalance(long value) {
      
      balance_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 账户余额
     * </pre>
     *
     * <code>int64 balance = 5;</code>
     */
    public Builder clearBalance() {
      
      balance_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetFinanceOverviewResp)
  }

  // @@protoc_insertion_point(class_scope:GetFinanceOverviewResp)
  private static final com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp();
  }

  public static com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetFinanceOverviewResp>
      PARSER = new com.google.protobuf.AbstractParser<GetFinanceOverviewResp>() {
    @java.lang.Override
    public GetFinanceOverviewResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetFinanceOverviewResp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetFinanceOverviewResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetFinanceOverviewResp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.itcast.bulls.stock.struct.netty.trade.GetFinanceOverviewResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

