// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockMessage.proto

package com.itcast.bulls.stock.struct.netty.trade;

/**
 * <pre>
 * 下单请求数据包
 * </pre>
 *
 * Protobuf type {@code PlaceOrderData}
 */
public  final class PlaceOrderData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PlaceOrderData)
    PlaceOrderDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PlaceOrderData.newBuilder() to construct.
  private PlaceOrderData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PlaceOrderData() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PlaceOrderData();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PlaceOrderData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            stockId_ = input.readInt64();
            break;
          }
          case 16: {

            direction_ = input.readInt32();
            break;
          }
          case 24: {

            type_ = input.readInt32();
            break;
          }
          case 32: {

            execVolume_ = input.readInt32();
            break;
          }
          case 40: {

            execPrice_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.itcast.bulls.stock.struct.netty.trade.StockMessageProto.internal_static_PlaceOrderData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.itcast.bulls.stock.struct.netty.trade.StockMessageProto.internal_static_PlaceOrderData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData.class, com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData.Builder.class);
  }

  public static final int STOCKID_FIELD_NUMBER = 1;
  private long stockId_;
  /**
   * <pre>
   * 股票产品ID
   * </pre>
   *
   * <code>int64 stockId = 1;</code>
   */
  public long getStockId() {
    return stockId_;
  }

  public static final int DIRECTION_FIELD_NUMBER = 2;
  private int direction_;
  /**
   * <pre>
   * 买卖方向
   * </pre>
   *
   * <code>int32 direction = 2;</code>
   */
  public int getDirection() {
    return direction_;
  }

  public static final int TYPE_FIELD_NUMBER = 3;
  private int type_;
  /**
   * <pre>
   * 挂单类型
   * </pre>
   *
   * <code>int32 type = 3;</code>
   */
  public int getType() {
    return type_;
  }

  public static final int EXECVOLUME_FIELD_NUMBER = 4;
  private int execVolume_;
  /**
   * <pre>
   * 请求数量
   * </pre>
   *
   * <code>int32 execVolume = 4;</code>
   */
  public int getExecVolume() {
    return execVolume_;
  }

  public static final int EXECPRICE_FIELD_NUMBER = 5;
  private long execPrice_;
  /**
   * <pre>
   * 请求价格
   * </pre>
   *
   * <code>int64 execPrice = 5;</code>
   */
  public long getExecPrice() {
    return execPrice_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (stockId_ != 0L) {
      output.writeInt64(1, stockId_);
    }
    if (direction_ != 0) {
      output.writeInt32(2, direction_);
    }
    if (type_ != 0) {
      output.writeInt32(3, type_);
    }
    if (execVolume_ != 0) {
      output.writeInt32(4, execVolume_);
    }
    if (execPrice_ != 0L) {
      output.writeInt64(5, execPrice_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (stockId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, stockId_);
    }
    if (direction_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, direction_);
    }
    if (type_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, type_);
    }
    if (execVolume_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, execVolume_);
    }
    if (execPrice_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, execPrice_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData)) {
      return super.equals(obj);
    }
    com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData other = (com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData) obj;

    if (getStockId()
        != other.getStockId()) return false;
    if (getDirection()
        != other.getDirection()) return false;
    if (getType()
        != other.getType()) return false;
    if (getExecVolume()
        != other.getExecVolume()) return false;
    if (getExecPrice()
        != other.getExecPrice()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STOCKID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStockId());
    hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
    hash = (53 * hash) + getDirection();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType();
    hash = (37 * hash) + EXECVOLUME_FIELD_NUMBER;
    hash = (53 * hash) + getExecVolume();
    hash = (37 * hash) + EXECPRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getExecPrice());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 下单请求数据包
   * </pre>
   *
   * Protobuf type {@code PlaceOrderData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PlaceOrderData)
      com.itcast.bulls.stock.struct.netty.trade.PlaceOrderDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.itcast.bulls.stock.struct.netty.trade.StockMessageProto.internal_static_PlaceOrderData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.itcast.bulls.stock.struct.netty.trade.StockMessageProto.internal_static_PlaceOrderData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData.class, com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData.Builder.class);
    }

    // Construct using com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      stockId_ = 0L;

      direction_ = 0;

      type_ = 0;

      execVolume_ = 0;

      execPrice_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.itcast.bulls.stock.struct.netty.trade.StockMessageProto.internal_static_PlaceOrderData_descriptor;
    }

    @java.lang.Override
    public com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData getDefaultInstanceForType() {
      return com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData.getDefaultInstance();
    }

    @java.lang.Override
    public com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData build() {
      com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData buildPartial() {
      com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData result = new com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData(this);
      result.stockId_ = stockId_;
      result.direction_ = direction_;
      result.type_ = type_;
      result.execVolume_ = execVolume_;
      result.execPrice_ = execPrice_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData) {
        return mergeFrom((com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData other) {
      if (other == com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData.getDefaultInstance()) return this;
      if (other.getStockId() != 0L) {
        setStockId(other.getStockId());
      }
      if (other.getDirection() != 0) {
        setDirection(other.getDirection());
      }
      if (other.getType() != 0) {
        setType(other.getType());
      }
      if (other.getExecVolume() != 0) {
        setExecVolume(other.getExecVolume());
      }
      if (other.getExecPrice() != 0L) {
        setExecPrice(other.getExecPrice());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long stockId_ ;
    /**
     * <pre>
     * 股票产品ID
     * </pre>
     *
     * <code>int64 stockId = 1;</code>
     */
    public long getStockId() {
      return stockId_;
    }
    /**
     * <pre>
     * 股票产品ID
     * </pre>
     *
     * <code>int64 stockId = 1;</code>
     */
    public Builder setStockId(long value) {
      
      stockId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 股票产品ID
     * </pre>
     *
     * <code>int64 stockId = 1;</code>
     */
    public Builder clearStockId() {
      
      stockId_ = 0L;
      onChanged();
      return this;
    }

    private int direction_ ;
    /**
     * <pre>
     * 买卖方向
     * </pre>
     *
     * <code>int32 direction = 2;</code>
     */
    public int getDirection() {
      return direction_;
    }
    /**
     * <pre>
     * 买卖方向
     * </pre>
     *
     * <code>int32 direction = 2;</code>
     */
    public Builder setDirection(int value) {
      
      direction_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 买卖方向
     * </pre>
     *
     * <code>int32 direction = 2;</code>
     */
    public Builder clearDirection() {
      
      direction_ = 0;
      onChanged();
      return this;
    }

    private int type_ ;
    /**
     * <pre>
     * 挂单类型
     * </pre>
     *
     * <code>int32 type = 3;</code>
     */
    public int getType() {
      return type_;
    }
    /**
     * <pre>
     * 挂单类型
     * </pre>
     *
     * <code>int32 type = 3;</code>
     */
    public Builder setType(int value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 挂单类型
     * </pre>
     *
     * <code>int32 type = 3;</code>
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private int execVolume_ ;
    /**
     * <pre>
     * 请求数量
     * </pre>
     *
     * <code>int32 execVolume = 4;</code>
     */
    public int getExecVolume() {
      return execVolume_;
    }
    /**
     * <pre>
     * 请求数量
     * </pre>
     *
     * <code>int32 execVolume = 4;</code>
     */
    public Builder setExecVolume(int value) {
      
      execVolume_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 请求数量
     * </pre>
     *
     * <code>int32 execVolume = 4;</code>
     */
    public Builder clearExecVolume() {
      
      execVolume_ = 0;
      onChanged();
      return this;
    }

    private long execPrice_ ;
    /**
     * <pre>
     * 请求价格
     * </pre>
     *
     * <code>int64 execPrice = 5;</code>
     */
    public long getExecPrice() {
      return execPrice_;
    }
    /**
     * <pre>
     * 请求价格
     * </pre>
     *
     * <code>int64 execPrice = 5;</code>
     */
    public Builder setExecPrice(long value) {
      
      execPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 请求价格
     * </pre>
     *
     * <code>int64 execPrice = 5;</code>
     */
    public Builder clearExecPrice() {
      
      execPrice_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PlaceOrderData)
  }

  // @@protoc_insertion_point(class_scope:PlaceOrderData)
  private static final com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData();
  }

  public static com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PlaceOrderData>
      PARSER = new com.google.protobuf.AbstractParser<PlaceOrderData>() {
    @java.lang.Override
    public PlaceOrderData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PlaceOrderData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PlaceOrderData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PlaceOrderData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.itcast.bulls.stock.struct.netty.trade.PlaceOrderData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

