// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockMessage.proto

package com.itcast.bulls.stock.struct.netty.trade;

public interface PlaceOrderRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PlaceOrderResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 dealId = 1;</code>
   */
  long getDealId();
}
