// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockHead.proto

package com.itcast.bulls.stock.struct.netty.trade;

public final class StockHeadProto {
  private StockHeadProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 协议版本
   * </pre>
   *
   * Protobuf enum {@code ProtoVer}
   */
  public enum ProtoVer
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>VER_1 = 0;</code>
     */
    VER_1(0),
    /**
     * <code>VER_2 = 1;</code>
     */
    VER_2(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>VER_1 = 0;</code>
     */
    public static final int VER_1_VALUE = 0;
    /**
     * <code>VER_2 = 1;</code>
     */
    public static final int VER_2_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ProtoVer valueOf(int value) {
      return forNumber(value);
    }

    public static ProtoVer forNumber(int value) {
      switch (value) {
        case 0: return VER_1;
        case 1: return VER_2;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ProtoVer>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ProtoVer> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProtoVer>() {
            public ProtoVer findValueByNumber(int number) {
              return ProtoVer.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final ProtoVer[] VALUES = values();

    public static ProtoVer valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ProtoVer(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ProtoVer)
  }

  /**
   * <pre>
   * 请求类型
   * </pre>
   *
   * Protobuf enum {@code RequestType}
   */
  public enum RequestType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 用户登陆
     * </pre>
     *
     * <code>USER_LOGIN = 0;</code>
     */
    USER_LOGIN(0),
    /**
     * <pre>
     * 用户下单
     * </pre>
     *
     * <code>PLACE_ORDER = 1;</code>
     */
    PLACE_ORDER(1),
    /**
     * <pre>
     * 实时行情数据
     * </pre>
     *
     * <code>QUOTE_REALTIME = 2;</code>
     */
    QUOTE_REALTIME(2),
    /**
     * <pre>
     * 获取K线数据
     * </pre>
     *
     * <code>QUOTE_KLINE = 3;</code>
     */
    QUOTE_KLINE(3),
    /**
     * <pre>
     * 用户撤单接口
     * </pre>
     *
     * <code>RECALL_ORDER = 4;</code>
     */
    RECALL_ORDER(4),
    /**
     * <pre>
     * 获取订单详情接口
     * </pre>
     *
     * <code>GET_ORDER = 5;</code>
     */
    GET_ORDER(5),
    /**
     * <pre>
     * 获取用户的持仓数据接口
     * </pre>
     *
     * <code>GET_ALL_POSITIONS = 6;</code>
     */
    GET_ALL_POSITIONS(6),
    /**
     * <pre>
     * 资金总览的接口
     * </pre>
     *
     * <code>GET_FINANCE_OVERVIEW = 7;</code>
     */
    GET_FINANCE_OVERVIEW(7),
    /**
     * <pre>
     *  获取账户交割单接口
     * </pre>
     *
     * <code>GET_ACCOUNT_SETTLEMENTS = 8;</code>
     */
    GET_ACCOUNT_SETTLEMENTS(8),
    /**
     * <pre>
     * 账户预警通知设置接口
     * </pre>
     *
     * <code>ACCOUNT_WARN_SETTING = 9;</code>
     */
    ACCOUNT_WARN_SETTING(9),
    /**
     * <pre>
     * 推送预警通知信息
     * </pre>
     *
     * <code>NOTIFY_WARN_MESSAGE = 10;</code>
     */
    NOTIFY_WARN_MESSAGE(10),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 用户登陆
     * </pre>
     *
     * <code>USER_LOGIN = 0;</code>
     */
    public static final int USER_LOGIN_VALUE = 0;
    /**
     * <pre>
     * 用户下单
     * </pre>
     *
     * <code>PLACE_ORDER = 1;</code>
     */
    public static final int PLACE_ORDER_VALUE = 1;
    /**
     * <pre>
     * 实时行情数据
     * </pre>
     *
     * <code>QUOTE_REALTIME = 2;</code>
     */
    public static final int QUOTE_REALTIME_VALUE = 2;
    /**
     * <pre>
     * 获取K线数据
     * </pre>
     *
     * <code>QUOTE_KLINE = 3;</code>
     */
    public static final int QUOTE_KLINE_VALUE = 3;
    /**
     * <pre>
     * 用户撤单接口
     * </pre>
     *
     * <code>RECALL_ORDER = 4;</code>
     */
    public static final int RECALL_ORDER_VALUE = 4;
    /**
     * <pre>
     * 获取订单详情接口
     * </pre>
     *
     * <code>GET_ORDER = 5;</code>
     */
    public static final int GET_ORDER_VALUE = 5;
    /**
     * <pre>
     * 获取用户的持仓数据接口
     * </pre>
     *
     * <code>GET_ALL_POSITIONS = 6;</code>
     */
    public static final int GET_ALL_POSITIONS_VALUE = 6;
    /**
     * <pre>
     * 资金总览的接口
     * </pre>
     *
     * <code>GET_FINANCE_OVERVIEW = 7;</code>
     */
    public static final int GET_FINANCE_OVERVIEW_VALUE = 7;
    /**
     * <pre>
     *  获取账户交割单接口
     * </pre>
     *
     * <code>GET_ACCOUNT_SETTLEMENTS = 8;</code>
     */
    public static final int GET_ACCOUNT_SETTLEMENTS_VALUE = 8;
    /**
     * <pre>
     * 账户预警通知设置接口
     * </pre>
     *
     * <code>ACCOUNT_WARN_SETTING = 9;</code>
     */
    public static final int ACCOUNT_WARN_SETTING_VALUE = 9;
    /**
     * <pre>
     * 推送预警通知信息
     * </pre>
     *
     * <code>NOTIFY_WARN_MESSAGE = 10;</code>
     */
    public static final int NOTIFY_WARN_MESSAGE_VALUE = 10;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RequestType valueOf(int value) {
      return forNumber(value);
    }

    public static RequestType forNumber(int value) {
      switch (value) {
        case 0: return USER_LOGIN;
        case 1: return PLACE_ORDER;
        case 2: return QUOTE_REALTIME;
        case 3: return QUOTE_KLINE;
        case 4: return RECALL_ORDER;
        case 5: return GET_ORDER;
        case 6: return GET_ALL_POSITIONS;
        case 7: return GET_FINANCE_OVERVIEW;
        case 8: return GET_ACCOUNT_SETTLEMENTS;
        case 9: return ACCOUNT_WARN_SETTING;
        case 10: return NOTIFY_WARN_MESSAGE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RequestType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
            public RequestType findValueByNumber(int number) {
              return RequestType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.getDescriptor().getEnumTypes().get(1);
    }

    private static final RequestType[] VALUES = values();

    public static RequestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RequestType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:RequestType)
  }

  public interface StockHeadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StockHead)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ProtoVer protoVer = 1;</code>
     */
    int getProtoVerValue();
    /**
     * <code>.ProtoVer protoVer = 1;</code>
     */
    com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.ProtoVer getProtoVer();

    /**
     * <code>.RequestType requestType = 2;</code>
     */
    int getRequestTypeValue();
    /**
     * <code>.RequestType requestType = 2;</code>
     */
    com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.RequestType getRequestType();

    /**
     * <pre>
     * 消息编号
     * </pre>
     *
     * <code>int64 seqId = 3;</code>
     */
    long getSeqId();

    /**
     * <pre>
     * 处理状态
     * </pre>
     *
     * <code>string status = 4;</code>
     */
    java.lang.String getStatus();
    /**
     * <pre>
     * 处理状态
     * </pre>
     *
     * <code>string status = 4;</code>
     */
    com.google.protobuf.ByteString
        getStatusBytes();
  }
  /**
   * <pre>
   * 头部
   * </pre>
   *
   * Protobuf type {@code StockHead}
   */
  public  static final class StockHead extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:StockHead)
      StockHeadOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StockHead.newBuilder() to construct.
    private StockHead(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StockHead() {
      protoVer_ = 0;
      requestType_ = 0;
      status_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StockHead();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StockHead(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              protoVer_ = rawValue;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              requestType_ = rawValue;
              break;
            }
            case 24: {

              seqId_ = input.readInt64();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              status_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.internal_static_StockHead_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.internal_static_StockHead_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead.class, com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead.Builder.class);
    }

    public static final int PROTOVER_FIELD_NUMBER = 1;
    private int protoVer_;
    /**
     * <code>.ProtoVer protoVer = 1;</code>
     */
    public int getProtoVerValue() {
      return protoVer_;
    }
    /**
     * <code>.ProtoVer protoVer = 1;</code>
     */
    public com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.ProtoVer getProtoVer() {
      @SuppressWarnings("deprecation")
      com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.ProtoVer result = com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.ProtoVer.valueOf(protoVer_);
      return result == null ? com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.ProtoVer.UNRECOGNIZED : result;
    }

    public static final int REQUESTTYPE_FIELD_NUMBER = 2;
    private int requestType_;
    /**
     * <code>.RequestType requestType = 2;</code>
     */
    public int getRequestTypeValue() {
      return requestType_;
    }
    /**
     * <code>.RequestType requestType = 2;</code>
     */
    public com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.RequestType getRequestType() {
      @SuppressWarnings("deprecation")
      com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.RequestType result = com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.RequestType.valueOf(requestType_);
      return result == null ? com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.RequestType.UNRECOGNIZED : result;
    }

    public static final int SEQID_FIELD_NUMBER = 3;
    private long seqId_;
    /**
     * <pre>
     * 消息编号
     * </pre>
     *
     * <code>int64 seqId = 3;</code>
     */
    public long getSeqId() {
      return seqId_;
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private volatile java.lang.Object status_;
    /**
     * <pre>
     * 处理状态
     * </pre>
     *
     * <code>string status = 4;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 处理状态
     * </pre>
     *
     * <code>string status = 4;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (protoVer_ != com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.ProtoVer.VER_1.getNumber()) {
        output.writeEnum(1, protoVer_);
      }
      if (requestType_ != com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.RequestType.USER_LOGIN.getNumber()) {
        output.writeEnum(2, requestType_);
      }
      if (seqId_ != 0L) {
        output.writeInt64(3, seqId_);
      }
      if (!getStatusBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, status_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (protoVer_ != com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.ProtoVer.VER_1.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, protoVer_);
      }
      if (requestType_ != com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.RequestType.USER_LOGIN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, requestType_);
      }
      if (seqId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, seqId_);
      }
      if (!getStatusBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, status_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead)) {
        return super.equals(obj);
      }
      com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead other = (com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead) obj;

      if (protoVer_ != other.protoVer_) return false;
      if (requestType_ != other.requestType_) return false;
      if (getSeqId()
          != other.getSeqId()) return false;
      if (!getStatus()
          .equals(other.getStatus())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PROTOVER_FIELD_NUMBER;
      hash = (53 * hash) + protoVer_;
      hash = (37 * hash) + REQUESTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + requestType_;
      hash = (37 * hash) + SEQID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSeqId());
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 头部
     * </pre>
     *
     * Protobuf type {@code StockHead}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StockHead)
        com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHeadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.internal_static_StockHead_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.internal_static_StockHead_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead.class, com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead.Builder.class);
      }

      // Construct using com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        protoVer_ = 0;

        requestType_ = 0;

        seqId_ = 0L;

        status_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.internal_static_StockHead_descriptor;
      }

      @java.lang.Override
      public com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead getDefaultInstanceForType() {
        return com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead.getDefaultInstance();
      }

      @java.lang.Override
      public com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead build() {
        com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead buildPartial() {
        com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead result = new com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead(this);
        result.protoVer_ = protoVer_;
        result.requestType_ = requestType_;
        result.seqId_ = seqId_;
        result.status_ = status_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead) {
          return mergeFrom((com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead other) {
        if (other == com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead.getDefaultInstance()) return this;
        if (other.protoVer_ != 0) {
          setProtoVerValue(other.getProtoVerValue());
        }
        if (other.requestType_ != 0) {
          setRequestTypeValue(other.getRequestTypeValue());
        }
        if (other.getSeqId() != 0L) {
          setSeqId(other.getSeqId());
        }
        if (!other.getStatus().isEmpty()) {
          status_ = other.status_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int protoVer_ = 0;
      /**
       * <code>.ProtoVer protoVer = 1;</code>
       */
      public int getProtoVerValue() {
        return protoVer_;
      }
      /**
       * <code>.ProtoVer protoVer = 1;</code>
       */
      public Builder setProtoVerValue(int value) {
        protoVer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.ProtoVer protoVer = 1;</code>
       */
      public com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.ProtoVer getProtoVer() {
        @SuppressWarnings("deprecation")
        com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.ProtoVer result = com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.ProtoVer.valueOf(protoVer_);
        return result == null ? com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.ProtoVer.UNRECOGNIZED : result;
      }
      /**
       * <code>.ProtoVer protoVer = 1;</code>
       */
      public Builder setProtoVer(com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.ProtoVer value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        protoVer_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ProtoVer protoVer = 1;</code>
       */
      public Builder clearProtoVer() {
        
        protoVer_ = 0;
        onChanged();
        return this;
      }

      private int requestType_ = 0;
      /**
       * <code>.RequestType requestType = 2;</code>
       */
      public int getRequestTypeValue() {
        return requestType_;
      }
      /**
       * <code>.RequestType requestType = 2;</code>
       */
      public Builder setRequestTypeValue(int value) {
        requestType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.RequestType requestType = 2;</code>
       */
      public com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.RequestType getRequestType() {
        @SuppressWarnings("deprecation")
        com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.RequestType result = com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.RequestType.valueOf(requestType_);
        return result == null ? com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.RequestType.UNRECOGNIZED : result;
      }
      /**
       * <code>.RequestType requestType = 2;</code>
       */
      public Builder setRequestType(com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        requestType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.RequestType requestType = 2;</code>
       */
      public Builder clearRequestType() {
        
        requestType_ = 0;
        onChanged();
        return this;
      }

      private long seqId_ ;
      /**
       * <pre>
       * 消息编号
       * </pre>
       *
       * <code>int64 seqId = 3;</code>
       */
      public long getSeqId() {
        return seqId_;
      }
      /**
       * <pre>
       * 消息编号
       * </pre>
       *
       * <code>int64 seqId = 3;</code>
       */
      public Builder setSeqId(long value) {
        
        seqId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息编号
       * </pre>
       *
       * <code>int64 seqId = 3;</code>
       */
      public Builder clearSeqId() {
        
        seqId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object status_ = "";
      /**
       * <pre>
       * 处理状态
       * </pre>
       *
       * <code>string status = 4;</code>
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 处理状态
       * </pre>
       *
       * <code>string status = 4;</code>
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 处理状态
       * </pre>
       *
       * <code>string status = 4;</code>
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 处理状态
       * </pre>
       *
       * <code>string status = 4;</code>
       */
      public Builder clearStatus() {
        
        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 处理状态
       * </pre>
       *
       * <code>string status = 4;</code>
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        status_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:StockHead)
    }

    // @@protoc_insertion_point(class_scope:StockHead)
    private static final com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead();
    }

    public static com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StockHead>
        PARSER = new com.google.protobuf.AbstractParser<StockHead>() {
      @java.lang.Override
      public StockHead parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StockHead(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StockHead> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StockHead> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.StockHead getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StockHead_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StockHead_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017StockHead.proto\"j\n\tStockHead\022\033\n\010protoV" +
      "er\030\001 \001(\0162\t.ProtoVer\022!\n\013requestType\030\002 \001(\016" +
      "2\014.RequestType\022\r\n\005seqId\030\003 \001(\003\022\016\n\006status\030" +
      "\004 \001(\t* \n\010ProtoVer\022\t\n\005VER_1\020\000\022\t\n\005VER_2\020\001*" +
      "\365\001\n\013RequestType\022\016\n\nUSER_LOGIN\020\000\022\017\n\013PLACE" +
      "_ORDER\020\001\022\022\n\016QUOTE_REALTIME\020\002\022\017\n\013QUOTE_KL" +
      "INE\020\003\022\020\n\014RECALL_ORDER\020\004\022\r\n\tGET_ORDER\020\005\022\025" +
      "\n\021GET_ALL_POSITIONS\020\006\022\030\n\024GET_FINANCE_OVE" +
      "RVIEW\020\007\022\033\n\027GET_ACCOUNT_SETTLEMENTS\020\010\022\030\n\024" +
      "ACCOUNT_WARN_SETTING\020\t\022\027\n\023NOTIFY_WARN_ME" +
      "SSAGE\020\nB;\n)com.itcast.bulls.stock.struct" +
      ".netty.tradeB\016StockHeadProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_StockHead_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_StockHead_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StockHead_descriptor,
        new java.lang.String[] { "ProtoVer", "RequestType", "SeqId", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
