package com.itcast.bulls.stock.entity.office;

import java.io.Serializable;

/**
 * 股票分时行情报价表
 * 
 * office.t_trade_stock_quote_last
 *
 *
 * @mbg.generated Fri May 08 15:22:22 CST 2020
 */
public class Tradestockquotelast implements Serializable {
    /**
     * 主键标识
     */
    private Integer id;

    /**
     * 产品ID
     */
    private Long stockid;

    /**
     * 产品编号
     */
    private String stockcode;

    /**
     * 产品名称
     */
    private String stockname;

    /**
     * 买方报价（一档）
     */
    private Long pricebid1;

    /**
     * 买方报价（二档）
     */
    private Long pricebid2;

    /**
     * 买方报价（三档）
     */
    private Long pricebid3;

    /**
     * 买方报价（四档）
     */
    private Long pricebid4;

    /**
     * 买方报价（五档）
     */
    private Long pricebid5;

    /**
     * 买方数量（一档）
     */
    private Long volumebid1;

    /**
     * 买方数量（二档）
     */
    private Long volumebid2;

    /**
     * 买方数量（三档）
     */
    private Long volumebid3;

    /**
     * 买方数量（四档）
     */
    private Long volumebid4;

    /**
     * 买方数量（五档）
     */
    private Long volumebid5;

    /**
     * 卖方报价（一档）
     */
    private Long priceask1;

    /**
     * 卖方报价（二档）
     */
    private Long priceask2;

    /**
     * 卖方报价（三档）
     */
    private Long priceask3;

    /**
     * 卖方报价（四档）
     */
    private Long priceask4;

    /**
     * 卖方报价（五档）
     */
    private Long priceask5;

    /**
     * 卖方数量（一档）
     */
    private Long volumeask1;

    /**
     * 卖方数量（二档）
     */
    private Long volumeask2;

    /**
     * 卖方数量（三档）
     */
    private Long volumeask3;

    /**
     * 卖方数量（四档）
     */
    private Long volumeask4;

    /**
     * 卖方数量（五档）
     */
    private Long volumeask5;

    /**
     * 当前价格
     */
    private Long lastprice;

    /**
     * 当前成交量
     */
    private Long volume;

    /**
     * 当前成交金额
     */
    private Long amount;

    /**
     * 报价时间
     */
    private Long time;

    /**
     */
    private Long openprice;

    /**
     */
    private Long lastcloseprice;

    /**
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * 主键标识
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_last.id
     *
     * @param id the value for office.t_trade_stock_quote_last.id
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 产品ID
     */
    public Long getStockid() {
        return stockid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_last.stockid
     *
     * @param stockid the value for office.t_trade_stock_quote_last.stockid
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setStockid(Long stockid) {
        this.stockid = stockid;
    }

    /**
     * 产品编号
     */
    public String getStockcode() {
        return stockcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_last.stockcode
     *
     * @param stockcode the value for office.t_trade_stock_quote_last.stockcode
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setStockcode(String stockcode) {
        this.stockcode = stockcode == null ? null : stockcode.trim();
    }

    /**
     * 产品名称
     */
    public String getStockname() {
        return stockname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_last.stockname
     *
     * @param stockname the value for office.t_trade_stock_quote_last.stockname
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setStockname(String stockname) {
        this.stockname = stockname == null ? null : stockname.trim();
    }

    /**
     * 买方报价（一档）
     */
    public Long getPricebid1() {
        return pricebid1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_last.pricebid1
     *
     * @param pricebid1 the value for office.t_trade_stock_quote_last.pricebid1
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setPricebid1(Long pricebid1) {
        this.pricebid1 = pricebid1;
    }

    /**
     * 买方报价（二档）
     */
    public Long getPricebid2() {
        return pricebid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_last.pricebid2
     *
     * @param pricebid2 the value for office.t_trade_stock_quote_last.pricebid2
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setPricebid2(Long pricebid2) {
        this.pricebid2 = pricebid2;
    }

    /**
     * 买方报价（三档）
     */
    public Long getPricebid3() {
        return pricebid3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_last.pricebid3
     *
     * @param pricebid3 the value for office.t_trade_stock_quote_last.pricebid3
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setPricebid3(Long pricebid3) {
        this.pricebid3 = pricebid3;
    }

    /**
     * 买方报价（四档）
     */
    public Long getPricebid4() {
        return pricebid4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_last.pricebid4
     *
     * @param pricebid4 the value for office.t_trade_stock_quote_last.pricebid4
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setPricebid4(Long pricebid4) {
        this.pricebid4 = pricebid4;
    }

    /**
     * 买方报价（五档）
     */
    public Long getPricebid5() {
        return pricebid5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_last.pricebid5
     *
     * @param pricebid5 the value for office.t_trade_stock_quote_last.pricebid5
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setPricebid5(Long pricebid5) {
        this.pricebid5 = pricebid5;
    }

    /**
     * 买方数量（一档）
     */
    public Long getVolumebid1() {
        return volumebid1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_last.volumebid1
     *
     * @param volumebid1 the value for office.t_trade_stock_quote_last.volumebid1
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setVolumebid1(Long volumebid1) {
        this.volumebid1 = volumebid1;
    }

    /**
     * 买方数量（二档）
     */
    public Long getVolumebid2() {
        return volumebid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_last.volumebid2
     *
     * @param volumebid2 the value for office.t_trade_stock_quote_last.volumebid2
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setVolumebid2(Long volumebid2) {
        this.volumebid2 = volumebid2;
    }

    /**
     * 买方数量（三档）
     */
    public Long getVolumebid3() {
        return volumebid3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_last.volumebid3
     *
     * @param volumebid3 the value for office.t_trade_stock_quote_last.volumebid3
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setVolumebid3(Long volumebid3) {
        this.volumebid3 = volumebid3;
    }

    /**
     * 买方数量（四档）
     */
    public Long getVolumebid4() {
        return volumebid4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_last.volumebid4
     *
     * @param volumebid4 the value for office.t_trade_stock_quote_last.volumebid4
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setVolumebid4(Long volumebid4) {
        this.volumebid4 = volumebid4;
    }

    /**
     * 买方数量（五档）
     */
    public Long getVolumebid5() {
        return volumebid5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_last.volumebid5
     *
     * @param volumebid5 the value for office.t_trade_stock_quote_last.volumebid5
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setVolumebid5(Long volumebid5) {
        this.volumebid5 = volumebid5;
    }

    /**
     * 卖方报价（一档）
     */
    public Long getPriceask1() {
        return priceask1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_last.priceask1
     *
     * @param priceask1 the value for office.t_trade_stock_quote_last.priceask1
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setPriceask1(Long priceask1) {
        this.priceask1 = priceask1;
    }

    /**
     * 卖方报价（二档）
     */
    public Long getPriceask2() {
        return priceask2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_last.priceask2
     *
     * @param priceask2 the value for office.t_trade_stock_quote_last.priceask2
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setPriceask2(Long priceask2) {
        this.priceask2 = priceask2;
    }

    /**
     * 卖方报价（三档）
     */
    public Long getPriceask3() {
        return priceask3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_last.priceask3
     *
     * @param priceask3 the value for office.t_trade_stock_quote_last.priceask3
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setPriceask3(Long priceask3) {
        this.priceask3 = priceask3;
    }

    /**
     * 卖方报价（四档）
     */
    public Long getPriceask4() {
        return priceask4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_last.priceask4
     *
     * @param priceask4 the value for office.t_trade_stock_quote_last.priceask4
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setPriceask4(Long priceask4) {
        this.priceask4 = priceask4;
    }

    /**
     * 卖方报价（五档）
     */
    public Long getPriceask5() {
        return priceask5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_last.priceask5
     *
     * @param priceask5 the value for office.t_trade_stock_quote_last.priceask5
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setPriceask5(Long priceask5) {
        this.priceask5 = priceask5;
    }

    /**
     * 卖方数量（一档）
     */
    public Long getVolumeask1() {
        return volumeask1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_last.volumeask1
     *
     * @param volumeask1 the value for office.t_trade_stock_quote_last.volumeask1
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setVolumeask1(Long volumeask1) {
        this.volumeask1 = volumeask1;
    }

    /**
     * 卖方数量（二档）
     */
    public Long getVolumeask2() {
        return volumeask2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_last.volumeask2
     *
     * @param volumeask2 the value for office.t_trade_stock_quote_last.volumeask2
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setVolumeask2(Long volumeask2) {
        this.volumeask2 = volumeask2;
    }

    /**
     * 卖方数量（三档）
     */
    public Long getVolumeask3() {
        return volumeask3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_last.volumeask3
     *
     * @param volumeask3 the value for office.t_trade_stock_quote_last.volumeask3
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setVolumeask3(Long volumeask3) {
        this.volumeask3 = volumeask3;
    }

    /**
     * 卖方数量（四档）
     */
    public Long getVolumeask4() {
        return volumeask4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_last.volumeask4
     *
     * @param volumeask4 the value for office.t_trade_stock_quote_last.volumeask4
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setVolumeask4(Long volumeask4) {
        this.volumeask4 = volumeask4;
    }

    /**
     * 卖方数量（五档）
     */
    public Long getVolumeask5() {
        return volumeask5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_last.volumeask5
     *
     * @param volumeask5 the value for office.t_trade_stock_quote_last.volumeask5
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setVolumeask5(Long volumeask5) {
        this.volumeask5 = volumeask5;
    }

    /**
     * 当前价格
     */
    public Long getLastprice() {
        return lastprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_last.lastprice
     *
     * @param lastprice the value for office.t_trade_stock_quote_last.lastprice
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setLastprice(Long lastprice) {
        this.lastprice = lastprice;
    }

    /**
     * 当前成交量
     */
    public Long getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_last.volume
     *
     * @param volume the value for office.t_trade_stock_quote_last.volume
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setVolume(Long volume) {
        this.volume = volume;
    }

    /**
     * 当前成交金额
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_last.amount
     *
     * @param amount the value for office.t_trade_stock_quote_last.amount
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * 报价时间
     */
    public Long getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_last.time
     *
     * @param time the value for office.t_trade_stock_quote_last.time
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setTime(Long time) {
        this.time = time;
    }

    /**
     */
    public Long getOpenprice() {
        return openprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_last.openprice
     *
     * @param openprice the value for office.t_trade_stock_quote_last.openprice
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setOpenprice(Long openprice) {
        this.openprice = openprice;
    }

    /**
     */
    public Long getLastcloseprice() {
        return lastcloseprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_last.lastcloseprice
     *
     * @param lastcloseprice the value for office.t_trade_stock_quote_last.lastcloseprice
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setLastcloseprice(Long lastcloseprice) {
        this.lastcloseprice = lastcloseprice;
    }
}