package com.itcast.bulls.stock.entity.office;

import java.io.Serializable;

/**
 * 股票K线表
 * 
 * office.t_trade_stock_kline
 *
 *
 * @mbg.generated Fri May 08 15:22:22 CST 2020
 */
public class Tradestockkline implements Serializable {
    /**
     * 主键标识
     */
    private Integer id;

    /**
     * 产品ID
     */
    private Long stockid;

    /**
     * 产品编号
     */
    private String stockcode;

    /**
     * 产品名称
     */
    private String stockname;

    /**
     * 开盘价
     */
    private Long priceopen;

    /**
     * 最高价
     */
    private Long pricehigh;

    /**
     * 最低价
     */
    private Long pricelow;

    /**
     * 收盘价
     */
    private Long priceclose;

    /**
     * 成交量
     */
    private Long volume;

    /**
     * 成交金额
     */
    private Long amount;

    /**
     * 报价时间
     */
    private Long time;

    /**
     */
    private Long lastcloseprice;

    /**
     */
    private Long datatype;

    /**
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * 主键标识
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_kline.id
     *
     * @param id the value for office.t_trade_stock_kline.id
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 产品ID
     */
    public Long getStockid() {
        return stockid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_kline.stockid
     *
     * @param stockid the value for office.t_trade_stock_kline.stockid
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setStockid(Long stockid) {
        this.stockid = stockid;
    }

    /**
     * 产品编号
     */
    public String getStockcode() {
        return stockcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_kline.stockcode
     *
     * @param stockcode the value for office.t_trade_stock_kline.stockcode
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setStockcode(String stockcode) {
        this.stockcode = stockcode == null ? null : stockcode.trim();
    }

    /**
     * 产品名称
     */
    public String getStockname() {
        return stockname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_kline.stockname
     *
     * @param stockname the value for office.t_trade_stock_kline.stockname
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setStockname(String stockname) {
        this.stockname = stockname == null ? null : stockname.trim();
    }

    /**
     * 开盘价
     */
    public Long getPriceopen() {
        return priceopen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_kline.priceopen
     *
     * @param priceopen the value for office.t_trade_stock_kline.priceopen
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setPriceopen(Long priceopen) {
        this.priceopen = priceopen;
    }

    /**
     * 最高价
     */
    public Long getPricehigh() {
        return pricehigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_kline.pricehigh
     *
     * @param pricehigh the value for office.t_trade_stock_kline.pricehigh
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setPricehigh(Long pricehigh) {
        this.pricehigh = pricehigh;
    }

    /**
     * 最低价
     */
    public Long getPricelow() {
        return pricelow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_kline.pricelow
     *
     * @param pricelow the value for office.t_trade_stock_kline.pricelow
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setPricelow(Long pricelow) {
        this.pricelow = pricelow;
    }

    /**
     * 收盘价
     */
    public Long getPriceclose() {
        return priceclose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_kline.priceclose
     *
     * @param priceclose the value for office.t_trade_stock_kline.priceclose
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setPriceclose(Long priceclose) {
        this.priceclose = priceclose;
    }

    /**
     * 成交量
     */
    public Long getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_kline.volume
     *
     * @param volume the value for office.t_trade_stock_kline.volume
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setVolume(Long volume) {
        this.volume = volume;
    }

    /**
     * 成交金额
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_kline.amount
     *
     * @param amount the value for office.t_trade_stock_kline.amount
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * 报价时间
     */
    public Long getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_kline.time
     *
     * @param time the value for office.t_trade_stock_kline.time
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setTime(Long time) {
        this.time = time;
    }

    /**
     */
    public Long getLastcloseprice() {
        return lastcloseprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_kline.lastcloseprice
     *
     * @param lastcloseprice the value for office.t_trade_stock_kline.lastcloseprice
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setLastcloseprice(Long lastcloseprice) {
        this.lastcloseprice = lastcloseprice;
    }

    /**
     */
    public Long getDatatype() {
        return datatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_kline.datatype
     *
     * @param datatype the value for office.t_trade_stock_kline.datatype
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setDatatype(Long datatype) {
        this.datatype = datatype;
    }
}