package com.itcast.bulls.stock.entity.office;

import java.io.Serializable;

/**
 * 股票报价概要表
 * 
 * office.t_trade_stock_quote_summary
 *
 *
 * @mbg.generated Fri May 08 15:22:22 CST 2020
 */
public class Tradestockquotesummary implements Serializable {
    /**
     * 主键标识
     */
    private Integer id;

    /**
     * 产品ID
     */
    private Long stockid;

    /**
     * 产品编号
     */
    private String stockcode;

    /**
     * 产品名称
     */
    private String stockname;

    /**
     * 开盘价
     */
    private Long openprice;

    /**
     * 收盘价
     */
    private Long closeprice;

    /**
     * 开盘时间
     */
    private Long openpricetime;

    /**
     * 收盘时间
     */
    private Long closepricetime;

    /**
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * 主键标识
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_summary.id
     *
     * @param id the value for office.t_trade_stock_quote_summary.id
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 产品ID
     */
    public Long getStockid() {
        return stockid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_summary.stockid
     *
     * @param stockid the value for office.t_trade_stock_quote_summary.stockid
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setStockid(Long stockid) {
        this.stockid = stockid;
    }

    /**
     * 产品编号
     */
    public String getStockcode() {
        return stockcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_summary.stockcode
     *
     * @param stockcode the value for office.t_trade_stock_quote_summary.stockcode
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setStockcode(String stockcode) {
        this.stockcode = stockcode == null ? null : stockcode.trim();
    }

    /**
     * 产品名称
     */
    public String getStockname() {
        return stockname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_summary.stockname
     *
     * @param stockname the value for office.t_trade_stock_quote_summary.stockname
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setStockname(String stockname) {
        this.stockname = stockname == null ? null : stockname.trim();
    }

    /**
     * 开盘价
     */
    public Long getOpenprice() {
        return openprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_summary.openprice
     *
     * @param openprice the value for office.t_trade_stock_quote_summary.openprice
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setOpenprice(Long openprice) {
        this.openprice = openprice;
    }

    /**
     * 收盘价
     */
    public Long getCloseprice() {
        return closeprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_summary.closeprice
     *
     * @param closeprice the value for office.t_trade_stock_quote_summary.closeprice
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setCloseprice(Long closeprice) {
        this.closeprice = closeprice;
    }

    /**
     * 开盘时间
     */
    public Long getOpenpricetime() {
        return openpricetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_summary.openpricetime
     *
     * @param openpricetime the value for office.t_trade_stock_quote_summary.openpricetime
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setOpenpricetime(Long openpricetime) {
        this.openpricetime = openpricetime;
    }

    /**
     * 收盘时间
     */
    public Long getClosepricetime() {
        return closepricetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.t_trade_stock_quote_summary.closepricetime
     *
     * @param closepricetime the value for office.t_trade_stock_quote_summary.closepricetime
     *
     * @mbg.generated Fri May 08 15:22:22 CST 2020
     */
    public void setClosepricetime(Long closepricetime) {
        this.closepricetime = closepricetime;
    }
}