// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/StockProxyService.proto

package com.itcast.trade.stock.struct.grpc.trade;

public interface WarnMessageDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WarnMessageData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <pre>
   **
   * 用户ID
   * </pre>
   *
   * <code>int64 userId = 2;</code>
   */
  long getUserId();

  /**
   * <pre>
   **
   * 账户ID
   * </pre>
   *
   * <code>int64 accountId = 3;</code>
   */
  long getAccountId();

  /**
   * <pre>
   **
   * 预警类型 (0: 止损, 1:止盈)
   * </pre>
   *
   * <code>int32 warnType = 4;</code>
   */
  int getWarnType();

  /**
   * <pre>
   **
   * 通知内容
   * </pre>
   *
   * <code>string notifyContent = 5;</code>
   */
  java.lang.String getNotifyContent();
  /**
   * <pre>
   **
   * 通知内容
   * </pre>
   *
   * <code>string notifyContent = 5;</code>
   */
  com.google.protobuf.ByteString
      getNotifyContentBytes();
}
