// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/StockKlineService.proto

package com.itcast.bulls.stock.struct.grpc.quote;

public interface GetKlineReponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetKlineReponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>repeated .KlineData klineData = 3;</code>
   */
  java.util.List<com.itcast.bulls.stock.struct.grpc.quote.KlineData> 
      getKlineDataList();
  /**
   * <code>repeated .KlineData klineData = 3;</code>
   */
  com.itcast.bulls.stock.struct.grpc.quote.KlineData getKlineData(int index);
  /**
   * <code>repeated .KlineData klineData = 3;</code>
   */
  int getKlineDataCount();
  /**
   * <code>repeated .KlineData klineData = 3;</code>
   */
  java.util.List<? extends com.itcast.bulls.stock.struct.grpc.quote.KlineDataOrBuilder> 
      getKlineDataOrBuilderList();
  /**
   * <code>repeated .KlineData klineData = 3;</code>
   */
  com.itcast.bulls.stock.struct.grpc.quote.KlineDataOrBuilder getKlineDataOrBuilder(
      int index);
}
