// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/StockKlineService.proto

package com.itcast.bulls.stock.struct.grpc.quote;

/**
 * <pre>
 * 获取K线数据接口, 响应包接口
 * </pre>
 *
 * Protobuf type {@code GetKlineReponse}
 */
public  final class GetKlineReponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetKlineReponse)
    GetKlineReponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetKlineReponse.newBuilder() to construct.
  private GetKlineReponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetKlineReponse() {
    status_ = "";
    message_ = "";
    klineData_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetKlineReponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetKlineReponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            status_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              klineData_ = new java.util.ArrayList<com.itcast.bulls.stock.struct.grpc.quote.KlineData>();
              mutable_bitField0_ |= 0x00000001;
            }
            klineData_.add(
                input.readMessage(com.itcast.bulls.stock.struct.grpc.quote.KlineData.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        klineData_ = java.util.Collections.unmodifiableList(klineData_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.itcast.bulls.stock.struct.grpc.quote.StockKlineServiceProto.internal_static_GetKlineReponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.itcast.bulls.stock.struct.grpc.quote.StockKlineServiceProto.internal_static_GetKlineReponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse.class, com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse.Builder.class);
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  private volatile java.lang.Object status_;
  /**
   * <code>string status = 1;</code>
   */
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string status = 1;</code>
   */
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object message_;
  /**
   * <code>string message = 2;</code>
   */
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 2;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KLINEDATA_FIELD_NUMBER = 3;
  private java.util.List<com.itcast.bulls.stock.struct.grpc.quote.KlineData> klineData_;
  /**
   * <code>repeated .KlineData klineData = 3;</code>
   */
  public java.util.List<com.itcast.bulls.stock.struct.grpc.quote.KlineData> getKlineDataList() {
    return klineData_;
  }
  /**
   * <code>repeated .KlineData klineData = 3;</code>
   */
  public java.util.List<? extends com.itcast.bulls.stock.struct.grpc.quote.KlineDataOrBuilder> 
      getKlineDataOrBuilderList() {
    return klineData_;
  }
  /**
   * <code>repeated .KlineData klineData = 3;</code>
   */
  public int getKlineDataCount() {
    return klineData_.size();
  }
  /**
   * <code>repeated .KlineData klineData = 3;</code>
   */
  public com.itcast.bulls.stock.struct.grpc.quote.KlineData getKlineData(int index) {
    return klineData_.get(index);
  }
  /**
   * <code>repeated .KlineData klineData = 3;</code>
   */
  public com.itcast.bulls.stock.struct.grpc.quote.KlineDataOrBuilder getKlineDataOrBuilder(
      int index) {
    return klineData_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getStatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, status_);
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
    }
    for (int i = 0; i < klineData_.size(); i++) {
      output.writeMessage(3, klineData_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getStatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, status_);
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
    }
    for (int i = 0; i < klineData_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, klineData_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse)) {
      return super.equals(obj);
    }
    com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse other = (com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse) obj;

    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (!getKlineDataList()
        .equals(other.getKlineDataList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    if (getKlineDataCount() > 0) {
      hash = (37 * hash) + KLINEDATA_FIELD_NUMBER;
      hash = (53 * hash) + getKlineDataList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 获取K线数据接口, 响应包接口
   * </pre>
   *
   * Protobuf type {@code GetKlineReponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetKlineReponse)
      com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.itcast.bulls.stock.struct.grpc.quote.StockKlineServiceProto.internal_static_GetKlineReponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.itcast.bulls.stock.struct.grpc.quote.StockKlineServiceProto.internal_static_GetKlineReponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse.class, com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse.Builder.class);
    }

    // Construct using com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getKlineDataFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      status_ = "";

      message_ = "";

      if (klineDataBuilder_ == null) {
        klineData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        klineDataBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.itcast.bulls.stock.struct.grpc.quote.StockKlineServiceProto.internal_static_GetKlineReponse_descriptor;
    }

    @java.lang.Override
    public com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse getDefaultInstanceForType() {
      return com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse build() {
      com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse buildPartial() {
      com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse result = new com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse(this);
      int from_bitField0_ = bitField0_;
      result.status_ = status_;
      result.message_ = message_;
      if (klineDataBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          klineData_ = java.util.Collections.unmodifiableList(klineData_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.klineData_ = klineData_;
      } else {
        result.klineData_ = klineDataBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse) {
        return mergeFrom((com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse other) {
      if (other == com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse.getDefaultInstance()) return this;
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        onChanged();
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (klineDataBuilder_ == null) {
        if (!other.klineData_.isEmpty()) {
          if (klineData_.isEmpty()) {
            klineData_ = other.klineData_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureKlineDataIsMutable();
            klineData_.addAll(other.klineData_);
          }
          onChanged();
        }
      } else {
        if (!other.klineData_.isEmpty()) {
          if (klineDataBuilder_.isEmpty()) {
            klineDataBuilder_.dispose();
            klineDataBuilder_ = null;
            klineData_ = other.klineData_;
            bitField0_ = (bitField0_ & ~0x00000001);
            klineDataBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getKlineDataFieldBuilder() : null;
          } else {
            klineDataBuilder_.addAllMessages(other.klineData_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object status_ = "";
    /**
     * <code>string status = 1;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string status = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status = 1;</code>
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string status = 1;</code>
     */
    public Builder clearStatus() {
      
      status_ = getDefaultInstance().getStatus();
      onChanged();
      return this;
    }
    /**
     * <code>string status = 1;</code>
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      status_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.itcast.bulls.stock.struct.grpc.quote.KlineData> klineData_ =
      java.util.Collections.emptyList();
    private void ensureKlineDataIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        klineData_ = new java.util.ArrayList<com.itcast.bulls.stock.struct.grpc.quote.KlineData>(klineData_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.itcast.bulls.stock.struct.grpc.quote.KlineData, com.itcast.bulls.stock.struct.grpc.quote.KlineData.Builder, com.itcast.bulls.stock.struct.grpc.quote.KlineDataOrBuilder> klineDataBuilder_;

    /**
     * <code>repeated .KlineData klineData = 3;</code>
     */
    public java.util.List<com.itcast.bulls.stock.struct.grpc.quote.KlineData> getKlineDataList() {
      if (klineDataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(klineData_);
      } else {
        return klineDataBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .KlineData klineData = 3;</code>
     */
    public int getKlineDataCount() {
      if (klineDataBuilder_ == null) {
        return klineData_.size();
      } else {
        return klineDataBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .KlineData klineData = 3;</code>
     */
    public com.itcast.bulls.stock.struct.grpc.quote.KlineData getKlineData(int index) {
      if (klineDataBuilder_ == null) {
        return klineData_.get(index);
      } else {
        return klineDataBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .KlineData klineData = 3;</code>
     */
    public Builder setKlineData(
        int index, com.itcast.bulls.stock.struct.grpc.quote.KlineData value) {
      if (klineDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKlineDataIsMutable();
        klineData_.set(index, value);
        onChanged();
      } else {
        klineDataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .KlineData klineData = 3;</code>
     */
    public Builder setKlineData(
        int index, com.itcast.bulls.stock.struct.grpc.quote.KlineData.Builder builderForValue) {
      if (klineDataBuilder_ == null) {
        ensureKlineDataIsMutable();
        klineData_.set(index, builderForValue.build());
        onChanged();
      } else {
        klineDataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .KlineData klineData = 3;</code>
     */
    public Builder addKlineData(com.itcast.bulls.stock.struct.grpc.quote.KlineData value) {
      if (klineDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKlineDataIsMutable();
        klineData_.add(value);
        onChanged();
      } else {
        klineDataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .KlineData klineData = 3;</code>
     */
    public Builder addKlineData(
        int index, com.itcast.bulls.stock.struct.grpc.quote.KlineData value) {
      if (klineDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKlineDataIsMutable();
        klineData_.add(index, value);
        onChanged();
      } else {
        klineDataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .KlineData klineData = 3;</code>
     */
    public Builder addKlineData(
        com.itcast.bulls.stock.struct.grpc.quote.KlineData.Builder builderForValue) {
      if (klineDataBuilder_ == null) {
        ensureKlineDataIsMutable();
        klineData_.add(builderForValue.build());
        onChanged();
      } else {
        klineDataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .KlineData klineData = 3;</code>
     */
    public Builder addKlineData(
        int index, com.itcast.bulls.stock.struct.grpc.quote.KlineData.Builder builderForValue) {
      if (klineDataBuilder_ == null) {
        ensureKlineDataIsMutable();
        klineData_.add(index, builderForValue.build());
        onChanged();
      } else {
        klineDataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .KlineData klineData = 3;</code>
     */
    public Builder addAllKlineData(
        java.lang.Iterable<? extends com.itcast.bulls.stock.struct.grpc.quote.KlineData> values) {
      if (klineDataBuilder_ == null) {
        ensureKlineDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, klineData_);
        onChanged();
      } else {
        klineDataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .KlineData klineData = 3;</code>
     */
    public Builder clearKlineData() {
      if (klineDataBuilder_ == null) {
        klineData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        klineDataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .KlineData klineData = 3;</code>
     */
    public Builder removeKlineData(int index) {
      if (klineDataBuilder_ == null) {
        ensureKlineDataIsMutable();
        klineData_.remove(index);
        onChanged();
      } else {
        klineDataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .KlineData klineData = 3;</code>
     */
    public com.itcast.bulls.stock.struct.grpc.quote.KlineData.Builder getKlineDataBuilder(
        int index) {
      return getKlineDataFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .KlineData klineData = 3;</code>
     */
    public com.itcast.bulls.stock.struct.grpc.quote.KlineDataOrBuilder getKlineDataOrBuilder(
        int index) {
      if (klineDataBuilder_ == null) {
        return klineData_.get(index);  } else {
        return klineDataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .KlineData klineData = 3;</code>
     */
    public java.util.List<? extends com.itcast.bulls.stock.struct.grpc.quote.KlineDataOrBuilder> 
         getKlineDataOrBuilderList() {
      if (klineDataBuilder_ != null) {
        return klineDataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(klineData_);
      }
    }
    /**
     * <code>repeated .KlineData klineData = 3;</code>
     */
    public com.itcast.bulls.stock.struct.grpc.quote.KlineData.Builder addKlineDataBuilder() {
      return getKlineDataFieldBuilder().addBuilder(
          com.itcast.bulls.stock.struct.grpc.quote.KlineData.getDefaultInstance());
    }
    /**
     * <code>repeated .KlineData klineData = 3;</code>
     */
    public com.itcast.bulls.stock.struct.grpc.quote.KlineData.Builder addKlineDataBuilder(
        int index) {
      return getKlineDataFieldBuilder().addBuilder(
          index, com.itcast.bulls.stock.struct.grpc.quote.KlineData.getDefaultInstance());
    }
    /**
     * <code>repeated .KlineData klineData = 3;</code>
     */
    public java.util.List<com.itcast.bulls.stock.struct.grpc.quote.KlineData.Builder> 
         getKlineDataBuilderList() {
      return getKlineDataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.itcast.bulls.stock.struct.grpc.quote.KlineData, com.itcast.bulls.stock.struct.grpc.quote.KlineData.Builder, com.itcast.bulls.stock.struct.grpc.quote.KlineDataOrBuilder> 
        getKlineDataFieldBuilder() {
      if (klineDataBuilder_ == null) {
        klineDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.itcast.bulls.stock.struct.grpc.quote.KlineData, com.itcast.bulls.stock.struct.grpc.quote.KlineData.Builder, com.itcast.bulls.stock.struct.grpc.quote.KlineDataOrBuilder>(
                klineData_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        klineData_ = null;
      }
      return klineDataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetKlineReponse)
  }

  // @@protoc_insertion_point(class_scope:GetKlineReponse)
  private static final com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse();
  }

  public static com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetKlineReponse>
      PARSER = new com.google.protobuf.AbstractParser<GetKlineReponse>() {
    @java.lang.Override
    public GetKlineReponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetKlineReponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetKlineReponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetKlineReponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.itcast.bulls.stock.struct.grpc.quote.GetKlineReponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

