// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/StockKlineService.proto

package com.itcast.bulls.stock.struct.grpc.quote;

public interface GetKlineRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetKlineRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 stockId = 1;</code>
   */
  long getStockId();

  /**
   * <code>string stockCode = 2;</code>
   */
  java.lang.String getStockCode();
  /**
   * <code>string stockCode = 2;</code>
   */
  com.google.protobuf.ByteString
      getStockCodeBytes();

  /**
   * <code>int64 timeStart = 3;</code>
   */
  long getTimeStart();

  /**
   * <code>int64 timeEnd = 4;</code>
   */
  long getTimeEnd();
}
