// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/StockKlineService.proto

package com.itcast.bulls.stock.struct.grpc.quote;

/**
 * <pre>
 * 获取K线数据接口， 返回的数据包结构
 * </pre>
 *
 * Protobuf type {@code KlineData}
 */
public  final class KlineData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:KlineData)
    KlineDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use KlineData.newBuilder() to construct.
  private KlineData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private KlineData() {
    stockCode_ = "";
    stockName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new KlineData();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private KlineData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            stockId_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            stockCode_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            stockName_ = s;
            break;
          }
          case 32: {

            priceOpen_ = input.readInt64();
            break;
          }
          case 40: {

            priceHigh_ = input.readInt64();
            break;
          }
          case 48: {

            priceLow_ = input.readInt64();
            break;
          }
          case 56: {

            priceClose_ = input.readInt64();
            break;
          }
          case 64: {

            volume_ = input.readInt64();
            break;
          }
          case 72: {

            amount_ = input.readInt64();
            break;
          }
          case 80: {

            time_ = input.readInt64();
            break;
          }
          case 88: {

            lastClosePrice_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.itcast.bulls.stock.struct.grpc.quote.StockKlineServiceProto.internal_static_KlineData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.itcast.bulls.stock.struct.grpc.quote.StockKlineServiceProto.internal_static_KlineData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.itcast.bulls.stock.struct.grpc.quote.KlineData.class, com.itcast.bulls.stock.struct.grpc.quote.KlineData.Builder.class);
  }

  public static final int STOCKID_FIELD_NUMBER = 1;
  private long stockId_;
  /**
   * <pre>
   * 产品ID
   * </pre>
   *
   * <code>int64 stockId = 1;</code>
   */
  public long getStockId() {
    return stockId_;
  }

  public static final int STOCKCODE_FIELD_NUMBER = 2;
  private volatile java.lang.Object stockCode_;
  /**
   * <pre>
   * 产品编号
   * </pre>
   *
   * <code>string stockCode = 2;</code>
   */
  public java.lang.String getStockCode() {
    java.lang.Object ref = stockCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stockCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 产品编号
   * </pre>
   *
   * <code>string stockCode = 2;</code>
   */
  public com.google.protobuf.ByteString
      getStockCodeBytes() {
    java.lang.Object ref = stockCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stockCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STOCKNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object stockName_;
  /**
   * <pre>
   * 产品名称
   * </pre>
   *
   * <code>string stockName = 3;</code>
   */
  public java.lang.String getStockName() {
    java.lang.Object ref = stockName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stockName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 产品名称
   * </pre>
   *
   * <code>string stockName = 3;</code>
   */
  public com.google.protobuf.ByteString
      getStockNameBytes() {
    java.lang.Object ref = stockName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stockName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRICEOPEN_FIELD_NUMBER = 4;
  private long priceOpen_;
  /**
   * <pre>
   * 开盘价
   * </pre>
   *
   * <code>int64 priceOpen = 4;</code>
   */
  public long getPriceOpen() {
    return priceOpen_;
  }

  public static final int PRICEHIGH_FIELD_NUMBER = 5;
  private long priceHigh_;
  /**
   * <pre>
   * 最高价
   * </pre>
   *
   * <code>int64 priceHigh = 5;</code>
   */
  public long getPriceHigh() {
    return priceHigh_;
  }

  public static final int PRICELOW_FIELD_NUMBER = 6;
  private long priceLow_;
  /**
   * <pre>
   * 最低价
   * </pre>
   *
   * <code>int64 priceLow = 6;</code>
   */
  public long getPriceLow() {
    return priceLow_;
  }

  public static final int PRICECLOSE_FIELD_NUMBER = 7;
  private long priceClose_;
  /**
   * <pre>
   * 收盘价
   * </pre>
   *
   * <code>int64 priceClose = 7;</code>
   */
  public long getPriceClose() {
    return priceClose_;
  }

  public static final int VOLUME_FIELD_NUMBER = 8;
  private long volume_;
  /**
   * <pre>
   * 成交量
   * </pre>
   *
   * <code>int64 volume = 8;</code>
   */
  public long getVolume() {
    return volume_;
  }

  public static final int AMOUNT_FIELD_NUMBER = 9;
  private long amount_;
  /**
   * <pre>
   * 成交金额
   * </pre>
   *
   * <code>int64 amount = 9;</code>
   */
  public long getAmount() {
    return amount_;
  }

  public static final int TIME_FIELD_NUMBER = 10;
  private long time_;
  /**
   * <pre>
   * 报价时间
   * </pre>
   *
   * <code>int64 time = 10;</code>
   */
  public long getTime() {
    return time_;
  }

  public static final int LASTCLOSEPRICE_FIELD_NUMBER = 11;
  private long lastClosePrice_;
  /**
   * <pre>
   * 作日的收盘价
   * </pre>
   *
   * <code>int64 lastClosePrice = 11;</code>
   */
  public long getLastClosePrice() {
    return lastClosePrice_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (stockId_ != 0L) {
      output.writeInt64(1, stockId_);
    }
    if (!getStockCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, stockCode_);
    }
    if (!getStockNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, stockName_);
    }
    if (priceOpen_ != 0L) {
      output.writeInt64(4, priceOpen_);
    }
    if (priceHigh_ != 0L) {
      output.writeInt64(5, priceHigh_);
    }
    if (priceLow_ != 0L) {
      output.writeInt64(6, priceLow_);
    }
    if (priceClose_ != 0L) {
      output.writeInt64(7, priceClose_);
    }
    if (volume_ != 0L) {
      output.writeInt64(8, volume_);
    }
    if (amount_ != 0L) {
      output.writeInt64(9, amount_);
    }
    if (time_ != 0L) {
      output.writeInt64(10, time_);
    }
    if (lastClosePrice_ != 0L) {
      output.writeInt64(11, lastClosePrice_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (stockId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, stockId_);
    }
    if (!getStockCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, stockCode_);
    }
    if (!getStockNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, stockName_);
    }
    if (priceOpen_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, priceOpen_);
    }
    if (priceHigh_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, priceHigh_);
    }
    if (priceLow_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, priceLow_);
    }
    if (priceClose_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, priceClose_);
    }
    if (volume_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, volume_);
    }
    if (amount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, amount_);
    }
    if (time_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(10, time_);
    }
    if (lastClosePrice_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(11, lastClosePrice_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.itcast.bulls.stock.struct.grpc.quote.KlineData)) {
      return super.equals(obj);
    }
    com.itcast.bulls.stock.struct.grpc.quote.KlineData other = (com.itcast.bulls.stock.struct.grpc.quote.KlineData) obj;

    if (getStockId()
        != other.getStockId()) return false;
    if (!getStockCode()
        .equals(other.getStockCode())) return false;
    if (!getStockName()
        .equals(other.getStockName())) return false;
    if (getPriceOpen()
        != other.getPriceOpen()) return false;
    if (getPriceHigh()
        != other.getPriceHigh()) return false;
    if (getPriceLow()
        != other.getPriceLow()) return false;
    if (getPriceClose()
        != other.getPriceClose()) return false;
    if (getVolume()
        != other.getVolume()) return false;
    if (getAmount()
        != other.getAmount()) return false;
    if (getTime()
        != other.getTime()) return false;
    if (getLastClosePrice()
        != other.getLastClosePrice()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STOCKID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStockId());
    hash = (37 * hash) + STOCKCODE_FIELD_NUMBER;
    hash = (53 * hash) + getStockCode().hashCode();
    hash = (37 * hash) + STOCKNAME_FIELD_NUMBER;
    hash = (53 * hash) + getStockName().hashCode();
    hash = (37 * hash) + PRICEOPEN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPriceOpen());
    hash = (37 * hash) + PRICEHIGH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPriceHigh());
    hash = (37 * hash) + PRICELOW_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPriceLow());
    hash = (37 * hash) + PRICECLOSE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPriceClose());
    hash = (37 * hash) + VOLUME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getVolume());
    hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAmount());
    hash = (37 * hash) + TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTime());
    hash = (37 * hash) + LASTCLOSEPRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastClosePrice());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.itcast.bulls.stock.struct.grpc.quote.KlineData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.itcast.bulls.stock.struct.grpc.quote.KlineData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.itcast.bulls.stock.struct.grpc.quote.KlineData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.itcast.bulls.stock.struct.grpc.quote.KlineData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.itcast.bulls.stock.struct.grpc.quote.KlineData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.itcast.bulls.stock.struct.grpc.quote.KlineData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.itcast.bulls.stock.struct.grpc.quote.KlineData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.itcast.bulls.stock.struct.grpc.quote.KlineData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.itcast.bulls.stock.struct.grpc.quote.KlineData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.itcast.bulls.stock.struct.grpc.quote.KlineData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.itcast.bulls.stock.struct.grpc.quote.KlineData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.itcast.bulls.stock.struct.grpc.quote.KlineData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.itcast.bulls.stock.struct.grpc.quote.KlineData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 获取K线数据接口， 返回的数据包结构
   * </pre>
   *
   * Protobuf type {@code KlineData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:KlineData)
      com.itcast.bulls.stock.struct.grpc.quote.KlineDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.itcast.bulls.stock.struct.grpc.quote.StockKlineServiceProto.internal_static_KlineData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.itcast.bulls.stock.struct.grpc.quote.StockKlineServiceProto.internal_static_KlineData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.itcast.bulls.stock.struct.grpc.quote.KlineData.class, com.itcast.bulls.stock.struct.grpc.quote.KlineData.Builder.class);
    }

    // Construct using com.itcast.bulls.stock.struct.grpc.quote.KlineData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      stockId_ = 0L;

      stockCode_ = "";

      stockName_ = "";

      priceOpen_ = 0L;

      priceHigh_ = 0L;

      priceLow_ = 0L;

      priceClose_ = 0L;

      volume_ = 0L;

      amount_ = 0L;

      time_ = 0L;

      lastClosePrice_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.itcast.bulls.stock.struct.grpc.quote.StockKlineServiceProto.internal_static_KlineData_descriptor;
    }

    @java.lang.Override
    public com.itcast.bulls.stock.struct.grpc.quote.KlineData getDefaultInstanceForType() {
      return com.itcast.bulls.stock.struct.grpc.quote.KlineData.getDefaultInstance();
    }

    @java.lang.Override
    public com.itcast.bulls.stock.struct.grpc.quote.KlineData build() {
      com.itcast.bulls.stock.struct.grpc.quote.KlineData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.itcast.bulls.stock.struct.grpc.quote.KlineData buildPartial() {
      com.itcast.bulls.stock.struct.grpc.quote.KlineData result = new com.itcast.bulls.stock.struct.grpc.quote.KlineData(this);
      result.stockId_ = stockId_;
      result.stockCode_ = stockCode_;
      result.stockName_ = stockName_;
      result.priceOpen_ = priceOpen_;
      result.priceHigh_ = priceHigh_;
      result.priceLow_ = priceLow_;
      result.priceClose_ = priceClose_;
      result.volume_ = volume_;
      result.amount_ = amount_;
      result.time_ = time_;
      result.lastClosePrice_ = lastClosePrice_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.itcast.bulls.stock.struct.grpc.quote.KlineData) {
        return mergeFrom((com.itcast.bulls.stock.struct.grpc.quote.KlineData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.itcast.bulls.stock.struct.grpc.quote.KlineData other) {
      if (other == com.itcast.bulls.stock.struct.grpc.quote.KlineData.getDefaultInstance()) return this;
      if (other.getStockId() != 0L) {
        setStockId(other.getStockId());
      }
      if (!other.getStockCode().isEmpty()) {
        stockCode_ = other.stockCode_;
        onChanged();
      }
      if (!other.getStockName().isEmpty()) {
        stockName_ = other.stockName_;
        onChanged();
      }
      if (other.getPriceOpen() != 0L) {
        setPriceOpen(other.getPriceOpen());
      }
      if (other.getPriceHigh() != 0L) {
        setPriceHigh(other.getPriceHigh());
      }
      if (other.getPriceLow() != 0L) {
        setPriceLow(other.getPriceLow());
      }
      if (other.getPriceClose() != 0L) {
        setPriceClose(other.getPriceClose());
      }
      if (other.getVolume() != 0L) {
        setVolume(other.getVolume());
      }
      if (other.getAmount() != 0L) {
        setAmount(other.getAmount());
      }
      if (other.getTime() != 0L) {
        setTime(other.getTime());
      }
      if (other.getLastClosePrice() != 0L) {
        setLastClosePrice(other.getLastClosePrice());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.itcast.bulls.stock.struct.grpc.quote.KlineData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.itcast.bulls.stock.struct.grpc.quote.KlineData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long stockId_ ;
    /**
     * <pre>
     * 产品ID
     * </pre>
     *
     * <code>int64 stockId = 1;</code>
     */
    public long getStockId() {
      return stockId_;
    }
    /**
     * <pre>
     * 产品ID
     * </pre>
     *
     * <code>int64 stockId = 1;</code>
     */
    public Builder setStockId(long value) {
      
      stockId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 产品ID
     * </pre>
     *
     * <code>int64 stockId = 1;</code>
     */
    public Builder clearStockId() {
      
      stockId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object stockCode_ = "";
    /**
     * <pre>
     * 产品编号
     * </pre>
     *
     * <code>string stockCode = 2;</code>
     */
    public java.lang.String getStockCode() {
      java.lang.Object ref = stockCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stockCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 产品编号
     * </pre>
     *
     * <code>string stockCode = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStockCodeBytes() {
      java.lang.Object ref = stockCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stockCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 产品编号
     * </pre>
     *
     * <code>string stockCode = 2;</code>
     */
    public Builder setStockCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      stockCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 产品编号
     * </pre>
     *
     * <code>string stockCode = 2;</code>
     */
    public Builder clearStockCode() {
      
      stockCode_ = getDefaultInstance().getStockCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 产品编号
     * </pre>
     *
     * <code>string stockCode = 2;</code>
     */
    public Builder setStockCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      stockCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object stockName_ = "";
    /**
     * <pre>
     * 产品名称
     * </pre>
     *
     * <code>string stockName = 3;</code>
     */
    public java.lang.String getStockName() {
      java.lang.Object ref = stockName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stockName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 产品名称
     * </pre>
     *
     * <code>string stockName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStockNameBytes() {
      java.lang.Object ref = stockName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stockName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 产品名称
     * </pre>
     *
     * <code>string stockName = 3;</code>
     */
    public Builder setStockName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      stockName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 产品名称
     * </pre>
     *
     * <code>string stockName = 3;</code>
     */
    public Builder clearStockName() {
      
      stockName_ = getDefaultInstance().getStockName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 产品名称
     * </pre>
     *
     * <code>string stockName = 3;</code>
     */
    public Builder setStockNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      stockName_ = value;
      onChanged();
      return this;
    }

    private long priceOpen_ ;
    /**
     * <pre>
     * 开盘价
     * </pre>
     *
     * <code>int64 priceOpen = 4;</code>
     */
    public long getPriceOpen() {
      return priceOpen_;
    }
    /**
     * <pre>
     * 开盘价
     * </pre>
     *
     * <code>int64 priceOpen = 4;</code>
     */
    public Builder setPriceOpen(long value) {
      
      priceOpen_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 开盘价
     * </pre>
     *
     * <code>int64 priceOpen = 4;</code>
     */
    public Builder clearPriceOpen() {
      
      priceOpen_ = 0L;
      onChanged();
      return this;
    }

    private long priceHigh_ ;
    /**
     * <pre>
     * 最高价
     * </pre>
     *
     * <code>int64 priceHigh = 5;</code>
     */
    public long getPriceHigh() {
      return priceHigh_;
    }
    /**
     * <pre>
     * 最高价
     * </pre>
     *
     * <code>int64 priceHigh = 5;</code>
     */
    public Builder setPriceHigh(long value) {
      
      priceHigh_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 最高价
     * </pre>
     *
     * <code>int64 priceHigh = 5;</code>
     */
    public Builder clearPriceHigh() {
      
      priceHigh_ = 0L;
      onChanged();
      return this;
    }

    private long priceLow_ ;
    /**
     * <pre>
     * 最低价
     * </pre>
     *
     * <code>int64 priceLow = 6;</code>
     */
    public long getPriceLow() {
      return priceLow_;
    }
    /**
     * <pre>
     * 最低价
     * </pre>
     *
     * <code>int64 priceLow = 6;</code>
     */
    public Builder setPriceLow(long value) {
      
      priceLow_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 最低价
     * </pre>
     *
     * <code>int64 priceLow = 6;</code>
     */
    public Builder clearPriceLow() {
      
      priceLow_ = 0L;
      onChanged();
      return this;
    }

    private long priceClose_ ;
    /**
     * <pre>
     * 收盘价
     * </pre>
     *
     * <code>int64 priceClose = 7;</code>
     */
    public long getPriceClose() {
      return priceClose_;
    }
    /**
     * <pre>
     * 收盘价
     * </pre>
     *
     * <code>int64 priceClose = 7;</code>
     */
    public Builder setPriceClose(long value) {
      
      priceClose_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 收盘价
     * </pre>
     *
     * <code>int64 priceClose = 7;</code>
     */
    public Builder clearPriceClose() {
      
      priceClose_ = 0L;
      onChanged();
      return this;
    }

    private long volume_ ;
    /**
     * <pre>
     * 成交量
     * </pre>
     *
     * <code>int64 volume = 8;</code>
     */
    public long getVolume() {
      return volume_;
    }
    /**
     * <pre>
     * 成交量
     * </pre>
     *
     * <code>int64 volume = 8;</code>
     */
    public Builder setVolume(long value) {
      
      volume_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 成交量
     * </pre>
     *
     * <code>int64 volume = 8;</code>
     */
    public Builder clearVolume() {
      
      volume_ = 0L;
      onChanged();
      return this;
    }

    private long amount_ ;
    /**
     * <pre>
     * 成交金额
     * </pre>
     *
     * <code>int64 amount = 9;</code>
     */
    public long getAmount() {
      return amount_;
    }
    /**
     * <pre>
     * 成交金额
     * </pre>
     *
     * <code>int64 amount = 9;</code>
     */
    public Builder setAmount(long value) {
      
      amount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 成交金额
     * </pre>
     *
     * <code>int64 amount = 9;</code>
     */
    public Builder clearAmount() {
      
      amount_ = 0L;
      onChanged();
      return this;
    }

    private long time_ ;
    /**
     * <pre>
     * 报价时间
     * </pre>
     *
     * <code>int64 time = 10;</code>
     */
    public long getTime() {
      return time_;
    }
    /**
     * <pre>
     * 报价时间
     * </pre>
     *
     * <code>int64 time = 10;</code>
     */
    public Builder setTime(long value) {
      
      time_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 报价时间
     * </pre>
     *
     * <code>int64 time = 10;</code>
     */
    public Builder clearTime() {
      
      time_ = 0L;
      onChanged();
      return this;
    }

    private long lastClosePrice_ ;
    /**
     * <pre>
     * 作日的收盘价
     * </pre>
     *
     * <code>int64 lastClosePrice = 11;</code>
     */
    public long getLastClosePrice() {
      return lastClosePrice_;
    }
    /**
     * <pre>
     * 作日的收盘价
     * </pre>
     *
     * <code>int64 lastClosePrice = 11;</code>
     */
    public Builder setLastClosePrice(long value) {
      
      lastClosePrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 作日的收盘价
     * </pre>
     *
     * <code>int64 lastClosePrice = 11;</code>
     */
    public Builder clearLastClosePrice() {
      
      lastClosePrice_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:KlineData)
  }

  // @@protoc_insertion_point(class_scope:KlineData)
  private static final com.itcast.bulls.stock.struct.grpc.quote.KlineData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.itcast.bulls.stock.struct.grpc.quote.KlineData();
  }

  public static com.itcast.bulls.stock.struct.grpc.quote.KlineData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<KlineData>
      PARSER = new com.google.protobuf.AbstractParser<KlineData>() {
    @java.lang.Override
    public KlineData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new KlineData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<KlineData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<KlineData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.itcast.bulls.stock.struct.grpc.quote.KlineData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

